### ISSUE TITLE
Uniform structure for future tooltips and strings

### ISSUE THREAD

**Issue by TheCutestSkinghoul** [Battle-Brothers-Legends/Legends-Bugs#102]
We are getting to a point where the features of the mod are outstripping our ability to document them. This means tooltips are becoming abridged or lacking critical info due to tooltip length.

Possible remedies;
A function that activates when holding a key while viewing a tooltip (like LALT) to expand that tooltip to reveal technical info

A new layout to tooltips, which may include predetermined fields or UI tweaks to display more info.

**Comment by LordMidas** [comment]
@Enduriel This could be done via MSU I guess. E.g. each perk can have 2 tooltips, one regular and one "detailed" and the user can press Alt to show the detailed one.

**Comment by Enduriel** [comment]
Yes, that was my thought as well.
