### ISSUE TITLE
Direwolves are too rare. Every beast contract is almost guaranteed to be mostly Nachzehrers and secondly Webknechts. Direwolves are almost extinct in such contracts.

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/Legends-Bugs#105]
Direwolves should spawn more often in beast contracts.

**Comment by Enduriel** [comment]
The relevant code is in roaming_beasts_contract.nut line 75 onwards, we can adjust this stuff, but imo what's there makes sense and direwolf contracts are just more common up north where players tend to spend less time right now.

**Comment by TheCutestSkinghoul** [comment]
> The relevant code is in roaming_beasts_contract.nut line 75 onwards, we can adjust this stuff, but imo what's there makes sense and direwolf contracts are just more common up north where players tend to spend less time right now.


Yeah I'm not sure what I'd change here. I'd maybe put it to a poll
