### ISSUE TITLE
Webknechts are the most hated beast in the community right now. They deal too much damage and give useless loot. Either make their loot more interesting or reduce their difficulty.

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/Legends-Bugs#106]

**Comment by TheCutestSkinghoul** [comment]
Considering mixing in additional loot like rings and other trinkets.

I have an idea on how to make these more interesting by introducing smaller xp consumables in the form of notes, journals, etc.

A brother 'reads' them (potion of knowledge style) and it gives them a small xp boost or maybe a little xp outright.

This stuff can be framed as lost books, parchment or adventurer's notes so they can be almost universally applied to justify their existence.
