### ISSUE TITLE
Game Crash at the end of the turn after using a smoke pot

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#11]
When I use a smoke pot in larger battles (Tested with 24 enemies and more than one of my people) then the game crashes at the end of the turn.

The relevant part from the log is this 

```
22:48:15 SQ INFO: Next round issued: 11
22:48:16 Core A critical exception occured.
22:48:16 Core Modules & Application Stacktrace: SymInit: Symbol-SearchPath: '.;S:\Games\Battle Brothers;S:\Games\Battle Brothers\win32;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Tom' OS-Version: 6.2.9200 () 0x100-0x1
22:48:16 Core Script Stacktrace:

Function: updateTileEffects -> scripts/entity/tactical/tactical_entity_manager.nut : 451
Function: turnsequencebar_onNextRound -> scripts/states/tactical_state.nut : 2420
Function: initNextRound -> scripts/ui/screens/tactical/modules/turn_sequence_bar/turn_sequence_bar.nut : 336
Function: update -> scripts/ui/screens/tactical/modules/turn_sequence_bar/turn_sequence_bar.nut : 1323
Function: onUpdate -> scripts/states/tactical_state.nut : 427

```

Here is my most detailed report to this issue including the log mentioned above:
https://discord.com/channels/547043336465154049/547044957547134979/864610520380342292
If you scroll a few posts down you can find my summary.

Here is a log by DeepBlueD having this bug
https://discord.com/channels/855921501286039582/856622921010905118/864735395370893333

Here is a report by Uberbagel having this bug
https://discord.com/channels/855921501286039582/856622921010905118/867961286938488842

**Comment by Enduriel** [comment]
Fixed [here](https://github.com/Battle-Brothers-Legends/Legends/commit/5b9b84af0d82abc16bf7fbeee5cc492010e4dfa7). Seems like it was an issue with a rushed merge by Rule back in August.
