### ISSUE TITLE
Softlock when ending camp as an event triggers on worldmap

### ISSUE THREAD

**Issue by TheCutestSkinghoul** [Battle-Brothers-Legends/Legends-Bugs#12]
**Versions**
All

**Describe the bug**
When you stop camping a screen should show up giving the camp report. If you do this as a random event triggers 

**To Reproduce**
Steps to reproduce the behaviour:
1. camp
2. have an event fire as you uncamp
3. Have a camp report you cannot dismiss

**Comment by Enduriel** [comment]
I'm unable to reproduce this behavior

**Comment by TheCutestSkinghoul** [comment]
Update: also happens with caravan carts being attacked while arriving at their desination.

**Comment by Enduriel** [comment]
Might have something to do with the whole Menu.hasBacksteps() stuff
