### ISSUE TITLE
The Balance perk should provide full bonus within an armor range instead of only at 35 fatigue armor. So for example it could be maximum between 30-35 armor. 

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/Legends-Bugs#123]
This will allow players to have easier time building the medium armor build in a layered armor setup - and also allows for more variation in the builds. @Uberbagel and @TheCutestSkinghoul please comment.

**Comment by Uberbagel** [comment]
Great change. Do it to it.
