### ISSUE TITLE
Each Camping Slot should have a max limit of bros assignable to it

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/Legends-Bugs#125]
Currently, the way most "efficient" players do camping is the following:
- Look I have an injured guy, and have a battle coming up, ok move 10 people to healing tent so that 10 people can pile up on a single bro and fix him up real fast.
- Oh look I just had a big battle and have tons of stuff to repair, move everyone to repair duty.
- Oh I am on a caravan, move everyone to gathering or training.
- And so on.

Basically, currently, camping revolves around moving most, if not all, of your bros to a single task. I don't like this. It also takes away the character and immersion of each camping duty, and makes it devolve to mere numbers.

Secondly, this makes it so that it is almost never worth it to purchase certain camp upgrades. E.g. I don't remember the last time I purchased a salvage tent upgrade because I can always salvage both "enough" and "fast enough" in the early game by assigning everyone to salvage, and in the late game I don't care about salvage because I can buy tools as money is a non-concern and other camping duties e.g. repair and training are more important.

I think each camping task should have a max number of bros assignable to it. This will put a greater emphasis on specialist bros in your company and promote more varied camping tasks. Ageldar the Fast is my Scout, he is always on scouting duty. Berengar is my blacksmith, always on repair and salvage duty etc.

The maximum number of bros for each tent should then be increaseable by purchasing the upgrade for that camping slot. This also makes it more meaningful to invest in camping upgrades for all the different camping tents.

**Comment by Uberbagel** [comment]
I second your analysis of the situation and I do like this solution. I'm curious of alternative ideas as well though.

**Comment by p0ss** [comment]
They should already have falloff, that was the original design intent. So you could stack people but it wouldn't be as good as sharing them around.  It was pretty tricky to explain in the UI though.

**Comment by Enduriel** [comment]
I don't think a hard cap is necessary or realistic, as Poss mentioned there's supposed to be scaling so perhaps that should be looked at and the UI tweaked to make this information more clear.

**Comment by LordMidas** [comment]
I don't think that diminishing returns solves the underlying issue here. There are three issues:

1. **Theory vs Practical:** In theory diminishing returns sounds like it works as "intended" but the fact is that most of the times the player needs to assign most bros to 1 or 2 tasks. After a battle, the repair, salvage, and maybe the healing tasks are gonna be important. On a caravan the training and gathering tasks are important as there is nothing to repair and usually nothing to salvage. So on and so forth. Therefore, even with diminishing returns, in most practical situations it still leads to spamming all or most bros into one or two tasks.
2. **Role-playing:** The current system is anti-immersion and anti-rpg. What I would prefer is that I have a bro in the company who I know as my blacksmith. And he's the guy who's doing the Repair and Salvage jobs. Then I have a Surgeon bro. Adelmar the Fast is my Scout. Horik is my Gatherer and Potion Brewer etc. Having hard limits on "some" camps where it makes sense creates the grounds for this kind of RP which is currently absent. With the retinues being "tools" now, there is even more precedent for this kind of RP. Unfortunately, currently, there is no such feeling and bros feel like numbers which you just slot into camping tasks all over the place, and bros have no character outside combat.
3. **Specialization and Game Balance:** Currently I never purchase the Salvage tent upgrade because in the early game money is precious and I can salvage fast enough as loot is low and I can put 10 bros into Salvage. In the late game I don't purchase Salvage tent because time is precious and I would rather put my bros on training. However, if we have a max 2 bro limit on Salvaging, it now puts a lot of emphasis on whether I want to purchase the Salvage upgrade because it may expand the limit to 4 and increase speed by 100% thereby giving me an overall 200% increase in salvage speed.

All 3 of the above issues are real issues which currently take away from the spirit of BB's fundamental role-playing aspect as a mercenary company management game. None of these issues is solved by the diminishing returns system. Therefore, I suggest that we put hard limits on certain camping tasks where it makes sense to have limits e.g. healing, repair, salvage etc.

**Comment by Uberbagel** [comment]
100 king this idea lit holla at ya fam

**Comment by TheCutestSkinghoul** [comment]
In this context I do see an argument to be made that having 20 guys heal one injury or some other task is kind of dumb.

But at the same time as poss said, it does curb stacking brothers already.
We could talk fixed limits for all or maybe larger or smaller limits for certain tents.
