### ISSUE TITLE
Bringing harmony between Camping and Retinue

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/Legends-Bugs#126]
**Describe what you think the current issue is**
Camping in Legends was created long before Overhype implemented the Retinue system. Hence, there is thematic overlap in what both systems are trying to accomplish, and what problems both systems are trying to address from a gameplay mechanics point of view. For example, Blacksmith retinue vs Salvage/Repair tent, Scout retinue vs Scout tent, Drill Sergeant retinue vs Training tent.

I'm not saying that they are equal. The point is that there is thematic overlap and both are trying to address the same thing i.e. mechanics related to bros other than combat.

When we converted Retinue from people to "tools", this was a major step in the right direction. I would like to take it one step further and make it even more inter-connected, intuitive, and better.

**Suggest how you'd fix this issue**
Remove the current "upgrade tents" that appear in markets for each of your camping slots. Instead, have the Retinue count as the upgrade for the relevant tent. For example, hiring the Blacksmith retinue (which is now some kind of tools) should "upgrade" your Repair and Salvage tents. Buying the Training Dummies retinue should upgrade your Training Grounds tent. The price of each retinue can be adjusted as necessary.

This system accomplishes two major goals:
- Ties both the camping and retinue systems together into one harmonious system.
- Puts more emphasis on company specialization as retinue slots are limited.

**Comment by Uberbagel** [comment]
I'm okay with this as long as we're careful with the transition and balance. It does mean there's pretty much a hard cap of 5 tools/camp upgrades though. So we have to be sure this is what we want to do.

**Comment by Enduriel** [comment]
Yeah I like this, easy enough to do and clears out some bloat. Best to do in the upcoming savebreaking build.
