### ISSUE TITLE
Crash When Fighting Nomads

### ISSUE THREAD

**Issue by wheatbread** [Battle-Brothers-Legends/Legends-Bugs#139]
Hi!  

I started a new game with version15.0.2.0 and everything was going ok until I got this contract to drive off nomads at the Red Sands Camp in the Glistening Flats.  (Contract obtained from Al-Hazif) Every time I click on the enemy camp to enter it, it goes to the loading screen and just sits there forever (15 min+) until I force exit it.   Repeated this 6x with the same result. 

This is the contract and the spot:

![image](https://user-images.githubusercontent.com/548824/144832540-f556a1ec-2a0d-4c09-9308-ba4a3ff8cffc.png)

These were the enemies that were to be loaded:

![image](https://user-images.githubusercontent.com/548824/144838458-38085b3a-2f4a-46d3-9bd8-e4305acc3641.png)

The only other mod I'm running is Smart Recruiter (Legends compatible version): https://www.nexusmods.com/battlebrothers/mods/172?tab=description    I tried to disable it to test but it wouldn't let me load the save without it.  

I reloaded a save without that contract and went on playing, for the next bit of info below:

*Edit:  I just now randomly ran into some nomads (Indebted and Nomad Slingers) running around and the same thing happened.  It stayed loading forever when it was going to load into the battle with them.   But this does not seem conclusive because after reloading, I ran into more enemies that were mostly Indebted and a few Nomad Slingers and the battle succeeded in loading.

**Comment by cshen6** [comment]
Can confirm this bug. Clean install, no other mods.

I run into it 3 times: 1 time when doing a caravan escort & attacked by nomad; two times getting contract to drive off nomads in camp. The battle loading screen just continue indefinitely. Very annoying and have to cancel contract to keep playing.

However, when random encountering with nomads, the battle seems to load fine.

**Comment by buronix** [comment]
I think Im experiencing the same bug, my crash log attached:
https://syncfiddle.net/fiddle/-MqWEkOUrPQqQXP9HM4X

![image](https://user-images.githubusercontent.com/8542684/145483817-a7708691-8441-499d-a326-eff06030f206.png)
[log.html.log](https://github.com/Battle-Brothers-Legends/Legends-Bugs/files/7688770/log.html.log)

**Comment by AlexologyEU** [comment]
Can confirm, issue only when fighting southern enemies. I tried starting an indebted company which loaded the first battle correctly. But other than that, I cannot face southern enemies.

**Comment by koofka** [comment]
Can confirm this same crash attempting to attack a nomad camp and also @cshen6 fix of rolling back to 15.0.1.24 was a fix for the same.

**Comment by koofka** [comment]
PSA, there is a fix for this crash on the #test_builds channel on the BB Legends mod discord.  There are also a couple test builds out as of today, so scroll up a bit.  Message link: https://discord.com/channels/547043336465154049/547427442818809881/915328538138271765
