### ISSUE TITLE
Nomad Helmet from beheaded wiederganger head is at wrong position [BUG]

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#141]
**Versions**
 - Game: 1.4.0.49
 - Legends Release 15.0.2.0

**Describe the bug**
I beheaded a wiederganger with my cleaver which wore a simple nomad helmet. The head that rolled onto a neighboring tile still kind of has the helmet. But the helmet has a very weird buggy looking offset to it..

**Screenshots**
![BehadedWiedergangerHelmet](https://user-images.githubusercontent.com/2252464/145781525-dc1f39ec-4dae-48f9-95a2-1ac024e27a55.PNG)

**Comment by TheCutestSkinghoul** [comment]
This is an issue with all helmets across all npcs due to how the sprites are flipped on death
