### ISSUE TITLE
[Suggestion] Add a new symbol in the Inventory/Formation view to show damaged armor on brothers

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#145]
**Is your feature request related to a problem? Please describe.**
It is very hard to spot whether a brother has damaged armour from the Formation Overview alone. For HP there is a red + symbol for anyone who doesn't have full HP.
So if you wanna check whose armour to replace after a fight you often need to select each brother separately to check their armour values. 

**Describe the solution you'd like**
Add a new symbol to every brother whose armour needs repair. I would personally only show it if the total durability is 90% or less of the maximum durability on armour, weapon and shield.

In the Screenshot I drew a very rough outline of a hammer. But there are already plenty of hammer or other tool symbols in the game that could be repurposed for this.

**Additional context**
![RepairNeededSymbol](https://user-images.githubusercontent.com/2252464/148122567-f570a834-2240-4b21-a045-568f60e82886.PNG)

**Comment by Tiryan122** [comment]
there was a mod for this a few years ago: [Armour Indicators](https://www.nexusmods.com/battlebrothers/mods/96)
never used it and it's probably not working in the current version

I'd suggest adding a show/hide button (similar to the mood toggle) if you decide to implement something like this.
