### ISSUE TITLE
[BUG] Adding Gravesman perk when wielding nothing results in an error.

### ISSUE THREAD

**Issue by PKozdra** [Battle-Brothers-Legends/Legends-Bugs#158]
**Versions**
 - Game: 1.5.0.12
 - Legends: 16.0.9

**Describe the bug**
When a perk Gravesman is added (perk.legend_specialist_shovel_skill) to an actor without a mainhand item equipped, an error occurs.

**To Reproduce**
1. Get a characters that has nothing equipped on mainhand slot.
2. Unlock 'Gravesman' perk.
3. An error occurs.

**Screenshots**

![image](https://user-images.githubusercontent.com/43813860/180337616-488e3930-63f5-4543-b17b-483adf72812c.png)

**Additional context**
To solve, add a constraint checking if item != null in code (...\scripts\skills\perks\perk_legend_specialist_shovel_skill.nut)

![image](https://user-images.githubusercontent.com/43813860/180338384-48c085cc-9ea2-4935-891c-e13c278abc4b.png)

**Comment by TheCutestSkinghoul** [comment]
Fixed in next build
