### ISSUE TITLE
Changing Overwhelm to make it worth the perk point again

### ISSUE THREAD

**Issue by MarcusVipsaniusAgrippa** [Battle-Brothers-Legends/Legends-Bugs#16]
**Describe what you think the current issue is**
Overwhelm on enemies was nerfed to -5% from -10% because the enemy overwhelming the player was considered too strong. However due to the generally low matt and ratt of enemies (up to 75 for lindwurms and chosen), this resulted in the player now only overwhelming for very little (up to 1-4 instead of 4-8), making the perk no longer worth the point spent. 

**Suggest how you'd fix this issue**
By making the perk no longer percentage based, but a straight -5 to matt and ratt, we can circumvent this. The effect for the AI is minimal, but is significantly stronger for the player, making it a worthwhile perk again. 

**Alternative solutions**
There could be two separate overwhelm perks, a -5% one for the opponents and a -10% one for the player. But this would this one would be an ugly solution and only lead to confusion I feel.

**Comment by TheCutestSkinghoul** [comment]
Proposed change;
Overwhelm -
	Keep stacks at at 5%
	Every stack of overwhelm increases damage taken by 3% on the target
        Resets to zero after their turn has passed

**Comment by Enduriel** [comment]
@TheCutestSkinghoul have you addressed this since?
