### ISSUE TITLE
Coven Leader never acts during her turn.  Any fight with coven leader can't progress from her turn.[BUG]

### ISSUE THREAD

**Issue by Scott-Stellmach** [Battle-Brothers-Legends/Legends-Bugs#162]
**Versions**
 - Game: [1.5.0.13]
 - Legends [16.1.5]

**Describe the bug**
Coven leader never completes her turn.  Ever

**To Reproduce**
1. Find any kind of hexe fight that has a coven leader
2. Play turns till it is coven leaders turn
3. The game never progresses the coven leaders turn
4. See the problem?? (no hate here, just want it to be known --love what you have done with the game)

**Screenshots**

**Additional context**
No matter what type of mission or event or interaction that I take with a coven leader the game plays through turns till it is the coven leaders turn then just never moves on.  As far as I can tell, she never makes a turn and the game gets stuck there.

I have done witch hunts from towns with missing children, the noble witch, unhold, alps mission, found them in the wild.  They all stop working at the coven leaders turn.

I am playing Beast Slayers campaign atm.  Day 199.  But this has been going on since the first time I found a coven leader.  I can't make some of the gear I want because I need the coven leader hair. 

I use the vortex MM.  List of mods is  MSU 1.2.2 , mod_hooks 21.1, and mod_legends_beta_16.1.5.  

GL and thanks for all the great work.

**Comment by TheCutestSkinghoul** [comment]
Fixed in testing. Will be in next build.
