### ISSUE TITLE
game crash after battle with trading caravan as allie [BUG]

### ISSUE THREAD

**Issue by KnightingaleZWN** [Battle-Brothers-Legends/Legends-Bugs#166]
**Versions**
 - Game: 1.5.0.15
 - Legends 17.0.9

**Describe the bug**
Initiate a battle with enemy along with trading caravan as allies, win the battle and then the game would be stuck at the loading screen. (I tried two battles, one with a barbarian king group and allied with 2 caravans, the other with 2 unholds and allied with 1 caravan)

**Comment by KnightingaleZWN** [comment]
additionally, even retreating from a battle with a caravan as allie will cause the game to stuck at loading screen.

**Comment by Tiger82pl** [comment]
Yes confirm issue. Same sadly..
