### ISSUE TITLE
The game crashes when the opponent tries to apply "Rotation"

### ISSUE THREAD

**Issue by MrDanpo** [Battle-Brothers-Legends/Legends-Bugs#167]
Game and Legends: last versions
The game crashes when the opponent tries to apply "Rotation"
Works with embalmed soldier 
Also worked in the previous version with barbarians chosen
I thought it was fixed(
![Crush](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/146201614/bd4685b0-8ebe-456a-a1b8-87fde0e75dc9)

**Comment by MrDanpo** [comment]
At the same time, when it is used by soldiers in the "noble war" everything is fine

**Comment by MrDanpo** [comment]
It happened again when it was used by a mercenary in a battle with the barbarian king 
v 18.2.3

**Comment by BreakyZ** [comment]
[mod_disable_rotation_behavouir.zip](https://github.com/user-attachments/files/17376750/mod_disable_rotation_behavouir.zip)

sorry about the delay - this is an error with ai rotation that we sadly can't fix - best we can do is allow you to disable rotation for ai
