### ISSUE TITLE
[BUG] Game freeze on AI necromancer's turn

### ISSUE THREAD

**Issue by Silica-Pathways** [Battle-Brothers-Legends/Legends-Bugs#169]
18.1.1, game froze on AI necromancer's turn, log - https://failiem.lv/u/3npyqfxaqw

It's repeatable. Savegame:
https://failiem.lv/u/3g6j3ctz48

Once you will get closer to both necromancers, the game will freeze on the turn of one of them.

**Comment by cofecofe3** [comment]
I can confirm, have the same issue. Could link my savegame tho if needed. Guess it's happening when necromancer wana cast review zombie 4-5th time in battle...

**Comment by Silica-Pathways** [comment]
Is this fixed for 18.2.2., @Hanter-19 ?

**Comment by Silica-Pathways** [comment]
Is this fixed in 1.8.2.3., @TheCutestSkinghoul ?

**Comment by Silica-Pathways** [comment]
Is this fixed in 1.8.2.4., @TheCutestSkinghoul ?

**Comment by docsnyder1234** [comment]
Just had the same Bug, doesn't seem to be fixed yet.

**Comment by JustJefff69420** [comment]
Same. The undead don't materialize and battle will not progress. Running 18.2.7

**Comment by LootyBoot** [comment]
Sigma

**Comment by regan32** [comment]
seems like i got same bug on 18.2.6, it's really annoing pls priority up.
In log file before crash..
`13:43:30
Script Error
the index 'TargetTile' does not exist
Function:
update -> C:\Users\alcat\Desktop\bbmodding\legends\new_build\scripts\camera\tactical_camera_director.nut : 101
Variables:
camera = Instance, this = Table
Function:
onUpdate -> scripts/states/tactical_state.nut : 445
Variables:
this = Table`
[log.zip](https://github.com/user-attachments/files/16028324/log.zip)
[autosave_2.zip](https://github.com/user-attachments/files/16028320/autosave_2.zip)

**Comment by BreakyZ** [comment]
Whoever is experiencing the targettile error - open your legends zip - delete the scripts/camera/ folder and it should fix itself

for ai rotation use this mod, the ai rotation logic is locked behind the exe so we cannot fix it, best we can do is disable - this will be cooked in the next legend build
[mod_disable_rotation_behavouir.zip](https://github.com/user-attachments/files/17376778/mod_disable_rotation_behavouir.zip)

if you are experiencing crashes when fighting undead - inside the release files there should be a patch, we apologize we didn't upload it here before
