### ISSUE TITLE
Making the assassin avatar an actually good killer

### ISSUE THREAD

**Issue by MarcusVipsaniusAgrippa** [Battle-Brothers-Legends/Legends-Bugs#17]
**Describe what you think the current issue is**
The assassin commander background starts out with some perks like "Lone Wolf" that really drive home the point of him being a ninja-like killer who works along. However, due to his mandatory "aggressive" trait and nor the underdog nor the battleheart perk, in a fight he gets quickly overwhelmed by up to -50mdef due to surround and "aggressive" trait. 
There are also some cosmetic changes I'd like to suggest while we're at it, painting a more thorough pictures of a professional killer that gets hired to spread fear amongst  Nomads as well as Northeners if the pay is right. 

**Suggest how you'd fix this issue**
Switch the mandatory trait for the assassin commander from "aggressive" (which doesn't really fit the stealthy-killer-route anyways) to "bloodthirsty": A professional always makes sure the target is dead! It's some nice flavor and gives those that want to travel solo for a while a nice bonus against wiedergangers as well. 

Add the following perks: 
- Favored Enemy Nomads: Multiple reasons for this: Not only does it make sense that city-states hire assassins to deal with Nomads. It also incentivizes the player to stay in his "homeland" and battle it out with bladedancers and other assassins while collecting their champions' famed weapons! 
- Battleheart: I feel like if anybody should know how to evade multiple attacks swiftly, it should be the assassin. With his low hp and light armor, he relies heavily on not getting hit too much. Compared to the berserker, lone wolf and crusader, this guy doesn't have the super heavy weapons, so it seems only fair that he should at least have the best mdef (next to the crusader). 
- Reach advantage: Bladedancers have it and I feel if any weapon makes sense with this perk it's the swordlance! Reason same as above. 
- Fearsome: What's scarier than a professional killer hired and determined to kill you and everybody that stands in your way? It makes only sense that opponents fear him who confidently takes on a whole group without batting an eye. Due to the Lone Wolf perk, fortified mind is probably not necessary to make this perk worthwhile. 

Perks to remove: 
- Favored Enemy Caravan: It makes little sense to me that highly trained and paid killers would go as low as robbing caravans on a regular basis. 
- Favored Enemy Raiders: Doesn't make much sense to me why an assassin would specialize on battling bandits in the North when he has no affiliation to Northern houses. The champion weapons are also not that interesting aside from 1h swords. 
- Rotate: Somebody usually working alone doesn't strike me as a good team player. 
- Windreader + bow + crossbow + throw perks + close combat archer : Let's be real: With so many points you need in matt, mdef, hp, ini and maybe even fat you're not gonna have points available to make a hybrid. These perks are basically just waste of space and I feel the assassin already has enough perks as is. Crossbows and Throwing weapons are also very unfitting for an assassin in BB's sense since they're Northern weapons. 
- Perfect Focus: An assassin doesn't usually have insane fat, so this perk feels like a waste as well, suggesting a variety an option that's just not viable. 
- Adrenaline: Also feels like a wasted perk since the assassin has really high ini and usually not enough fat to use it for more than one or two rounds at most. 

**Alternative solutions**
Nope, all my changes are perfect and definitely not subject to personal bias! :P

**Comment by TheCutestSkinghoul** [comment]
Assassin was given aggressive and no underdog/battleheart for a reason - because when he did have battleheart he was the strongest light armour fighter that didn't need any brothers to help them.

The purpose of aggressive is to allow the assassin to function as part of a group rather than a one man army.

fearsome and reach advantage may be worthwhile adding, but for the most part I think the assassin is well balanced as they are
