### ISSUE TITLE
[BUG] Retinue screen do not work with "Escaped slaves" origin

### ISSUE THREAD

**Issue by logunovjg** [Battle-Brothers-Legends/Legends-Bugs#170]
**Versions**
 - Game: 15.0.1.15
 - Legends: 18.1.1

**Describe the bug**
Retinue do not work if start "Escaped slaves" origin
On others origins it work without any problems "A new company" for example

**To Reproduce**
1. Start game on "Escaped slaves"
2. Get some renown
3. Click on "retinue" button
4. Click on "plus" button
5. Nothing happens

**Comment by sidness98** [comment]
I am having this same issue. Very tragic because i love my bros on this save 😔

**Comment by VatgrownHobo** [comment]
Having the same issue on "Random Party" start with version 18.2.6
