### ISSUE TITLE
[BUG] Game freezes on merc with Named 1-Handed Riposte Sword

### ISSUE THREAD

**Issue by Tissarr** [Battle-Brothers-Legends/Legends-Bugs#172]
- Game: [1.5.0.15]
 - Legends [18.2.2]

Game freezes when merc with Named 1-Handed Riposte Sword starts his turn and game rolls him to start it with riposte (the 18.2.2 new feature). I can still access the inventory, menu, options. The game doesn't allow me to use the merc; so I have to reload the auto save.
So using xBreditor I spawned myself some fencing named swords and it happens on any merc. (Also about half of spawned sword didn't show/had at all, the 'chance to start in riposte' stated)

I also run the game on mods that I don't think are interfering with new spawned weapons nor their stats. I can provide the list if necessary and the save.

**Comment by ViniciusAz** [comment]
I have the same problem. Ive got a named 1-h sword with 10% Chance to Riposte on Turn Start and everytime the turn start with riposte the game freeze...
![image](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/14865603/16962103-4d66-4e54-9702-fded9279b3a2)

**Comment by BreakyZ** [comment]
please provide logs in the future for all your issues - else this should be resolved in later versions
