### ISSUE TITLE
Game not updating to latest mod version[BUG]

### ISSUE THREAD

**Issue by GreyWulff-playing** [Battle-Brothers-Legends/Legends-Bugs#173]
**Versions**
 - Game: [18.1.1]
 - Legends [18.1.1 camps & contracts]

**Describe the bug**
game not updating to latest mod version

**To Reproduce**
1. downloaded mod 18.2.3
2. drop into file: SteamLibrary\steamapps\common\Battle Brothers\data
3. start up game
4. see attached photo
![error message - 17Feb2024](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/160358989/2c0952e7-2483-4717-a5d7-1edd664cce11)

**Screenshots**
![image](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/160358989/4ab23423-34b2-4a3d-ae94-6b519daa95c7)

**Comment by BreakyZ** [comment]
no log so can't help
