### ISSUE TITLE
Unique flail with "daze on hit" ability crush the game [BUG]

### ISSUE THREAD

**Issue by logunovjg** [Battle-Brothers-Legends/Legends-Bugs#175]
**Versions**
 - Game: [e.g. 1.4.0.49]
 - Legends [e.g. 15.0.1.15]

**Describe the bug**
When use unique flail

**To Reproduce**
Its difficult, but problem happens only with unique flail with "DAZE ON HIT" ability.
After loading save game several fights work well, but ...
Sometimes on attack with unique flail the game crush.
Sometimes brother with unique flail unable to attack, flail attack icon just dissapear. If you remove flail into inventory, you will be able to attack with VERY POWERFUL unarmed attack with about 80-120 damage on hit and great armour damage.
You need 5-10 fights to reproduce error.

**Comment by therealgoodstuff** [comment]
not sure if that is only true for that specific weapons. So far I learned from trying that any weapon with such an additional skill crashes the game for me, it is not only that flail. When I remove such a weapon and sell it all is good. I figured that out by saving and trying.

**Comment by BreakyZ** [comment]
this should be fixed in subsequent versions
