### ISSUE TITLE
Basilisk Necklace Save File Corruption [BUG]

### ISSUE THREAD

**Issue by Dart630** [Battle-Brothers-Legends/Legends-Bugs#176]
**Versions**
 - Game: 1.5.0.15
 - Legends 18.2.3

**Describe the bug**
Save corrupted when Basilisk Necklace is equipped on a brother. 

**To Reproduce**
1. Craft a Basilisk Trophy Necklace (I did so from the camp, not taxidermist)
2. Try to equip to a brother -> when I drag and drop into equipment slot and/or right-click to equip the necklace it doesn't *seem* to equip, the item still shows in stash but and now not interactable.
3. After closing and reopening inventory menu it is equipped on brother and interactable. Can unequip and interact as any other similar item.
4. If equipped to a brother when saving the file won't load and shows up as corrupt. The file will load if the necklace is in the stash at the time of saving.

**Comment by Dart630** [comment]
Seems that you guys are aware from the discord and a patch was issued! Yay and thanks for the awesome mod

**Comment by Silica-Pathways** [comment]
> Seems that you guys are aware from the discord and a patch was issued! Yay and thanks for the awesome mod

No, it seems they are not aware of the bugs. Necromancer bug, according to the changelog, has not been fixed in the last two patches.
