### ISSUE TITLE
Early bandit camp Wiedergangers were armored and well-armed [BALANCE]

### ISSUE THREAD

**Issue by TehemGo** [Battle-Brothers-Legends/Legends-Bugs#178]
I started a new run, as per usual, Vet/Vet/High Ironman unexplored.
After a few missions, I took a desert bandit camp mission, one skull. I can't say on what day it was, due to how death on Ironman works, but it must have been around day 10.
On my way there, the camp spawned a group of two Slingers and eleven Indebted, which is normal, and I dispatched them. It meant to me the bandit camp was about the normal difficulty.
I went back to the camp after healing up, and the text warned me that there were undead there, which is also quite frequent.
But when the battle opened, the eight Wiedergangers were too well-armed for so early in the game, even more so on a one skull mission. With them still being described as simple "Wiedergangers", not the Armored variant, they all wore mail (minus one) and wielded Scramasaxes, Axes and even a Two-handed Saif. At this stage, I can manage Clubs and bites, maybe a Militia Spear or two, and maybe even one one-handed third tier weapon, like an axe, a sword or a military-grade cleaver. But not a two-handed widowmaker an Outlaw would be a worthy opponent with to a 100-days old team.
Killed none before being buried in the sand.

Maybe make sure this mission spawns regular Indebted or Cutthroat/Slinger-level gear, not above ? It's the first time I run into this particular balance issue though. Maybe it has to do with the desert version of the base prompt ?

I'm running v1.5.0.15 Legends v18.2.4 with mods Hooks v 21 and Modern Hooks v0.4.10, after having checked both are Legends-compatible. It may be the source of the problem as well.

![banditcamp](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/69685886/b6ce8c87-07f5-4e7f-9fb1-4f491107d309)

**Comment by TehemGo** [comment]
Ran into the same problem. Vet/Vet settings, day 21, 2 skull mission, and the Necromancer had surrounded himself with 16 mail-armored Wiedergangers, although their weapons were tier #2 (maces, mallets and spears).
![necro desert bandits](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/69685886/ac4c061e-1c68-4cd2-87cf-3480b5231c64)

My hardest human opponents so far were Thugs.

The overall balance issues like this makes it far too hard to not get behind the curve when having to retreat in 1/3 fights.
I'm now running v1.5.0.15 Legends v18.2.3 with mods
- additional keybinds
- hyper blue
- Items and Recipes
- Modern Hooks
- MSU
- Settlement Situations MSU
- Swifter

**Comment by BreakyZ** [comment]
in 18.2.7 + wiedergangers will now spawn with a random amount of hp so they're less of a nuisance to fight
