### ISSUE TITLE
[BUG] the cabal start skill bug, when brothers die, 66% to be  resurrected but never work

### ISSUE THREAD

**Issue by SnowerII** [Battle-Brothers-Legends/Legends-Bugs#179]
**Versions**
 - Game: [e.g. 1.5.0.15]
 - Legends [e.g. 18.2.3]

**Describe the bug**
as title said, Cabal start bug,  Deathly Spectre skill, never work as will. cant  resurrected, same as new bro or those three starter

**Comment by BreakyZ** [comment]
update your legends version
