### ISSUE TITLE
Visually change Retreat-Button when enemy retreats

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#18]
**Problem:**
Sometimes players accidentally retreat from a battle even though they won it because they thought the enemy was already in the retreating state.
This happens mainly because the prompts both actions look very similar.

**Solution:**
When you get the prompt **The Enemy Retreats** but you choose **Run them down!** then the white flag at the top right should visually change indicating that you can from now on instantly end the battle whenever you like!
One Idea would be simply coloring it green.

**Comment by TheCutestSkinghoul** [comment]
Can do the art for this feature. Let me know what is needed.
