### ISSUE TITLE
[BUG] buying a donkey blocks inventory from opening

### ISSUE THREAD

**Issue by OldmanMagoo** [Battle-Brothers-Legends/Legends-Bugs#180]
**Versions**
 - Game: [1.5.0.15]
 - Legends [Chickens & Demons 18.2.4](https://github.com/Battle-Brothers-Legends/Legends-Bugs/releases/tag/18.2.4)

**Describe the bug**
started as beserker, bought a donkey, on ironman, save & exited game, reloaded savegame and then i could not open my inventory. 

maybe you can reproduce

**Comment by BreakyZ** [comment]
update your legends version - if you experience this again post a log otherwise we can't help or identify the problem
