### ISSUE TITLE
[BUG] "Glutton/Fat" events do not compile, breaking event manager

### ISSUE THREAD

**Issue by hamzah-hayat** [Battle-Brothers-Legends/Legends-Bugs#181]
**Versions**
 - Game: 1.5.0.15
 - Legends 18.2.5

**Describe the bug**
The following files
"scripts/events/events/glutton_gets_fat_event.cnut"
"scripts/events/events/good_food_variety_event.cnut"
"scripts/events/events/legends/legend_reserve_gets_fat_event.cnut"
each have a (copy-pasted) statement that looks like so:

```
if (this.bro.getFlags().get("IsSpecial") || this.bro.getFlags().get("IsPlayerCharacter") || this.bro.getBackground().getID() == "background.legend_puppet" || this.bro.getBackground().getID() == "background.legend_donkey")
{
  return;
}
```

This has been placed in the wrong part of the file (the "bro" variable does not exist).
This causes the event to fail, which also causes the event manager to fail, breaking all events from running.
To fix this, I would move the check statement into each events for loop eg (for the reserve brother gets fat event)

```
foreach( bro in brothers )
{
	if (bro.getFlags().get("IsSpecial") || bro.getFlags().get("IsPlayerCharacter") || bro.getBackground().getID() == "background.legend_puppet" || bro.getBackground().getID() == "background.legend_donkey")
	{
		continue;
	}
	if (bro.isInReserves())
	{
		if (!bro.getSkills().hasSkill("trait.gluttonous"))
		{
			candidates.push(bro);
		}
	}
}
```

**To Reproduce**
1. Start a Battle brothers campaign
2. Wait a few days
3. Check BB error log
4. Have no events fire.

**Screenshots**
Error log
![image](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/11432022/e5782a52-a451-43c2-b444-ea453563219c)

Further errors are generated like so:
![image](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/11432022/fc143029-8473-40bc-9542-06542d99faa1)

**Additional context**
The last release notes mention the following
"Player characters, special characters, puppets and donkeys can no longer get 'fat' or 'gluttonous' traits from events related to eating too much (in some cases, these instances may generate with these traits still)."
I believe that this directly relates to the error, this was coded incorrectly.

**Comment by BreakyZ** [comment]
sorry for the very late reply - these issues should be fixed with the 18.2.6
