### ISSUE TITLE
[BUG] Game crash after looting

### ISSUE THREAD

**Issue by giegand** [Battle-Brothers-Legends/Legends-Bugs#182]
**Versions**
 - Game: [1.5.0.1.5]
 - Legends [18.2.6]

Looting after a battle works without problems. Next time I want to save, game freezes and I get this error:

![image](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/170967184/c67f38dd-d7f6-4813-8153-4284b71bb608)

Restart game, I get this error:

![image](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/170967184/a86fd98a-ad2a-4696-ad06-64ef6789d836)

Savegame is corrupt. This occurs not after every combat. But if it occurs, it happens after every new try for this specific combat after loading a previous savegame or the autosave.

**Comment by giegand** [comment]
With Legends [18.2.7] no bug occured.

**Comment by truongHoangCong** [comment]
Same issue

**Comment by BreakyZ** [comment]
provide a log file as specified else i can't do anything
