### ISSUE TITLE
[BUG] Training Camp stops working over time

### ISSUE THREAD

**Issue by ACuriousPudding** [Battle-Brothers-Legends/Legends-Bugs#183]
**Versions**
 - Game: [e.g. 1.5.0.15]
 - Legends [16.3.3 Smoke & Faith]

**Describe the bug**
While camping on a late-game scaling beggar, the training camp no longer produces ANY results outside of increasing the XP gained in the next battle by 10% for any of the bros in the camp. Specifically, no XP gains for any of them, no perks, no trait increases. The last two things are and were fairly rare, but I currently have 10 bros in the training camp with a total effectiveness increase of ~250%. Most are above level 12, with one at level 25. Until very recently, the XP gains were consistent-ish, and traits and perks appeared infrequently. As of maybe 50 days ago, they stopped entirely.

When testing variations on the behavior, it seems that once bros hit that +15/+1 limit, having too many of them in the training camp causes everyone to stop gaining XP. If you remove all but the people below 12, they will gain xp and traits/perks as normal. There doesn't appear to be a way to get those above 12 to gain XP under any combination of bros. This was verified by tracking XP values prior to camping, not relying on the Camp Report output

**To Reproduce**
1. Have 23 bros above level 12 ranging from 12 to 25 with a fairly equal spread
2. Most bros in company should have reached +15 trait and +1 perk
3. Day 550
4. Training camp effectiveness over 225%
5. Assign more than 10 of them to the training camp
6. Camp for 1-2 days
7. End camp

Will check back soon in case more clarification is required, or if you need me to test a specific combination of events/conditions

**Comment by BreakyZ** [comment]
This was very likely fixed in later versions of the mod. You should update.
