### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kurogane1210** [Battle-Brothers-Legends/Legends-Bugs#184]
**Versions**
 - Game: [battle brothers]
 - Legends [Chickens & Demons 18.2.7]

**Describe the bug**
all battles regarding undead do not load. the game stays stuck on the loading screen. 
The cursor also does not move. 

**To Reproduce**
started a new game. Currently playing lone wolf. 
Seems to be any battle containing Wiedergangers, happens when attacking locations and when roaming undead initiate battle

**Comment by sirmik** [comment]
exactly the same problem +1

**Comment by Kallmegbernt** [comment]
I've found the exact same problem.
Can attack locations controlled by humans, but any undead seems to make the game stay stuck on the loading screen.

**Comment by ThorenRyder** [comment]
Yeah, same for me. Game freezes when attacking Wiederganger. Everything else seems fine.

**Comment by ilter1980** [comment]
+1 same here. And when necromancer summon dead battle stops, rised dead dont seen. you have to quit game for main screen

**Comment by Engkan296** [comment]
Same also here.When will this be fixed?Seems like its a prevalent bug.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Thanks buddy, fix works.
Hate this trend of hiding things in Discord.

**Comment by Silica-Pathways** [comment]
> i joined the discord. the hot fix there seems to fix the bug [zzz_mod_Official_Legends_patch_v3.zip](https://github.com/user-attachments/files/15837002/zzz_mod_Official_Legends_patch_v3.zip)

Does it also fix the AI necromancer turn freeze ?

And why did it took them half a year to fix this bug ?

**Comment by BreakyZ** [comment]
if you're experiencing the necromancer turn freeze: 

open your legends mod zip

delete scripts/camera/ folder
