### ISSUE TITLE
[BUG] stuck in loading camp battle

### ISSUE THREAD

**Issue by alecgonzales** [Battle-Brothers-Legends/Legends-Bugs#186]
**Versions**
 - Game: 1.5.0.15
 - Legends 18.2.7 Chickens & Demons

**Describe the bug**
I accepted a quest to clear a camp. When starting the battle, the screen gets stuck in loading (page with the tip)

**To Reproduce**
1. Load attached save
2. Click on camp with the coin icon
3. Enter battle

**Save File**
[crashing.zip](https://github.com/user-attachments/files/15862359/crashing.zip)

**Comment by Rymy2** [comment]
I have the same bug, and only some locations take forever to load. Only locations with Wiedergangers and Nachzehrers take forever but seeing the last changes i suspect its because of the zombies.

**Comment by zaxtin123** [comment]
> I have the same bug, and only some locations take forever to load. Only locations with Wiedergangers and Nachzehrers take forever but seeing the last changes i suspect its because of the zombies.

its always because the undead bro damn the old mod not have bug like this damn it

**Comment by regan32** [comment]
Try to disable UI mods, for enemy units detalization. (modern_hooks, tactical_pack, useful_pack, etc). That helped for me. There is log file in documents/battle brothers path, you may get information whitch mode is fail.

**Comment by cajstephens** [comment]
There's an official patch on the Legends discord that corrects the undead loading issue.

**Comment by zaxtin123** [comment]
> There's an official patch on the Legends discord that corrects the undead loading issue.

i cant join the discord can you somehow share the file maybe ?

**Comment by BreakyZ** [comment]
The discord link should work fine, but here's an alternative download link.

[zzz_mod_Official_Legends_patch_v4.zip](https://github.com/user-attachments/files/16150674/zzz_mod_Official_Legends_patch_v4.zip)
