### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by truongHoangCong** [Battle-Brothers-Legends/Legends-Bugs#187]
**Versions**
 - Game: [1.5.0.15

 - Legends 18.12.7]

**Describe the bug**
Crash when loading.

**To Reproduce**
1. Go to the desert map and do quests
2. Receive the task as attached
3. Quest as shown in the accompanying image, complete and get the next quest
4. Quick save and reload
5. errors as attached

**Screenshots**
![Screenshot 2024-06-18 005055](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/46306829/078a956c-e031-4c34-a21e-e916f0136999)
![Screenshot 2024-06-18 005038](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/46306829/e8bcc376-2c9f-436f-9d20-d8c669e0d904)
![Screenshot 2024-06-18 004831](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/46306829/41fa085d-4472-45d5-9a1d-e3cca6d4286a)
]

**Additional context**
Add any other context about the problem, such as links to a discord discussion, here.

**Comment by BreakyZ** [comment]
Please provide a log attached
