### ISSUE TITLE
[BUG] Necromancer cannot "raise undead"

### ISSUE THREAD

**Issue by Vushkinwt** [Battle-Brothers-Legends/Legends-Bugs#188]
**Versions**
 - Game: 1.5.0.15
 - Legends 18.2.7

**Describe the bug**
[BUG] Necromancer cannot "raise undead" as wiederganger does not appear and round stucks there.

**To Reproduce**
1. Play any match against necromancer
2. Kill someone
3. Wait him to use "raise undead"
4. Stuck

**Screenshots**
![bbnecro1](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/173604974/b00be0bf-f85a-4098-ab31-c434a454348e)
![Uploading bbnecro1.png…]()

**Comment by Vushkinwt** [comment]
![bbnecro1](https://github.com/Battle-Brothers-Legends/Legends-Bugs/assets/173604974/886ee364-71d3-4076-bab0-a3f0a72a9d6a)

**Comment by mako1974** [comment]
Hi, I want to confirm this bug also occurs in my game. Unable to complete Necro fight.

Best regards

**Comment by Silica-Pathways** [comment]
Necromancer fights have been bugged for half a year already, so good luck at getting them fixed.

**Comment by Silica-Pathways** [comment]
> > half a year already
> 
> half a year already ? did you know the best version of the mod with less bug ?

Unfortunately half a year ago when I resumed(!) playing BBL, the bug was already there, so I have no idea which is the last version without it. Legends devs have never responded to me here on Github nor on Steam.

**Comment by Josephseidita** [comment]
Samee thing happens to me. It really is impossible to play avoiding Necromancers and the associated bug. I hope legends developers will address this issue.

**Comment by Vyantic** [comment]
I remember the last version of Camp & Contracts (18.1.1) didn't have this issue, i had an old file of that version which i played for over 3 months and after a lot of Necromancer's battles this didn't happen once.

I guess some changes after the Chicken's & Demons release might broke something in the code. I hope they fix it.

**Comment by Vyantic** [comment]
> > half a year already
> 
> half a year already ? did you know the best version of the mod with less bug ?

I remember the last version of Camp & Contracts (18.1.1) didn't have this issue, i had an old file of that version which i played for over 3 months and after a lot of Necromancer's battles this didn't happen once.

**Comment by BreakyZ** [comment]
I apologize for the late reply, we provide a lot more timely support on our official discord.

you can use this patch

[zzz_mod_Official_Legends_patch_v4.zip](https://github.com/user-attachments/files/16150671/zzz_mod_Official_Legends_patch_v4.zip)

**Comment by Silica-Pathways** [comment]
> I apologize for the late reply, we provide a lot more timely support on our official discord.
> 
> you can use this patch
> 
> [zzz_mod_Official_Legends_patch_v4.zip](https://github.com/user-attachments/files/16150671/zzz_mod_Official_Legends_patch_v4.zip)

I boycott Discord due to it's RvW policy. Others likely have other reasons to not use it. I don't think a single game is a big enough reason for people to force themselves to use specific services.
GitHub, in comparison, does not engage itself into politics, therefore provides a neutral ground for communication, without compromising anyone's principles.

And, personally, I have no issue taking years long breaks from specific game, if for whatever bug Legends would become unplayable for some future version. I.e., I simply have hundreds of other games too. No offense.

And thanks for the fix. Better late than never, as they say.

**Comment by BreakyZ** [comment]
While true, github is not really intended as a communication platform.

Either way we'll try to attach patches in any future Release files and answer bug reports here faster.
