### ISSUE TITLE
[BUG] Wiedergangers are hella bugged.

### ISSUE THREAD

**Issue by LootyBoot** [Battle-Brothers-Legends/Legends-Bugs#189]
**Versions**
 - Game: 1.5.0.15
 - Legends 18.2.7

**Describe the bug**
If wiedergangers are present in an enemy party then the fight with them won't load. If there are no wiedergangers present but a necromancer tries to raise undead then the wiederganger bugs out something fierce, the enemies you kill become wiedergangers and then you can't target them with attacks but they can still attack you and have attacks of opportunity if you try to walk away. If the last person to act is a wiederganger then the whole fight freezes, not the game mind you, you can still hover over tiles for tooltips and access the menu, it's just that the turn order gets stuck and won't advance to the next round.

**To Reproduce**
1. Just go into any fight with a necromancer to test out the turn getting stuck after they raise a dead person.
2. Go into any fight with wiedergangers already present to test out the infinite loading screen.

**Additional context**
Apparently this has been a present bug since the early access days of battle brothers all the way back in 2015. The same bug has been fixed and fixed again and somehow it still finds it's way back.

**Comment by regan32** [comment]
By my expiriance, infinite loading screen usualy caused by UI mods, like tactical_pack or useful_pack. see the log file for errors.

**Comment by cajstephens** [comment]
> By my expiriance, infinite loading screen usualy caused by UI mods, like tactical_pack or useful_pack. see the log file for errors.

I've been having this issue as well, with nothing beyond Legends/MSU.

**Comment by eqfan592** [comment]
Having this exact same issue as well, only running Legends mod and MSU. Have to save before accepting any mission because if the mission happens to spawn undead or necros it basically breaks the game.

**Comment by LootyBoot** [comment]
Tried it without any additional mods and it still doesn't work, so no, it's a legends mod problem.

**Comment by BreakyZ** [comment]
Anyone having this issue - come to the official Legends discord and download patch4 from #latest_builds

**Comment by LootyBoot** [comment]
Sigma
