### ISSUE TITLE
Fix balance around the weapon "Chain" that spawns on Orc Young

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#19]
**Current issue:**
Orc Young spawn with the Legends-Exclusiv weapon **Chain** but the stats on it are extremly weak.
This makes those Orcs very easy to deal with

**Suggest how you'd fix this issue:**
- Remove **Chain** from being spawned on orcs

**Alternative solutions**
- Introduce a higher tier Orc-Exclusiv (with Fatigue penalty) version of the **Chain** that specifically spawns with Orc Young

**Comment by MarcusVipsaniusAgrippa** [comment]
I second this. Orc young with this chain are basically a free kill for the player as the only things they seem to hit often times are their allies.

**Comment by Enduriel** [comment]
Merc has moved the chain from spawning on orc young to their low (weaker) version, combined with a fix for their chain AI reported by Midas, they should be in a much better place so I will be marking this as fixed for now. Feel free to reopen this if you disagree after the next build is released.
