### ISSUE TITLE
escort caravan engange battle with undead [BUG]

### ISSUE THREAD

**Issue by zaxtin123** [Battle-Brothers-Legends/Legends-Bugs#190]
**Versions**
 - Game: [e.g. 1.5.0.15]
 - Legends [e.g. 15.0.1.15]

**Describe the bug**
stuck in loading when going to attack undead while escort caravan

**To Reproduce**
1. Go to 'escort caravan'
2. Click on 'engange battle with undead'
3. See error
4. only loading not start the fight 

**Screenshots**

**Additional context**
Add any other context about the problem, such as links to a discord discussion, here.

**Comment by Silica-Pathways** [comment]
Undead fights been bugged for half a year, good luck!

**Comment by zaxtin123** [comment]
any idea the best version mod for playing ? (for anyone read this)

**Comment by BreakyZ** [comment]
If you're able to come to the Official Legends Discord, we provide a lot better support there.

Use the following patch to fix the bug.
[zzz_mod_Official_Legends_patch_v4.zip](https://github.com/user-attachments/files/16150644/zzz_mod_Official_Legends_patch_v4.zip)
