### ISSUE TITLE
[BUG] Battle freezes on geist turn

### ISSUE THREAD

**Issue by regan32** [Battle-Brothers-Legends/Legends-Bugs#191]
**Versions**
 - Game: 1.5.0.1
 - Legends 18.2.6

**Describe the bug**
At 4-5 turn of battle game stuck on geist turn, then geist not in seeing range

**To Reproduce**
beggar+ scenario. battle in camp with undead + city militia (~50 units)
game freezes on geist turn at 4-5 game turn (geist in fog of war)

**Additional context**
Error in logs
`14:06:57
Script Error
the index 'TargetTile' does not exist
Function:
update -> C:\Users\alcat\Desktop\bbmodding\legends\new_build\scripts\camera\tactical_camera_director.nut : 101
Variables:
camera = Instance, this = Table
Function:
onUpdate -> scripts/states/tactical_state.nut : 445
Variables:
this = Table`
[log.zip](https://github.com/user-attachments/files/16028494/log.zip)
here is a save to reproduce: legends mode 18.2.6 + matchlocks 1.6.2 mode [autosave_2.zip](https://github.com/user-attachments/files/16028508/autosave_2.zip)

**Comment by tqb333** [comment]
I have the same error, but with stronghold mod and even solo vs udeads

**Comment by BreakyZ** [comment]
If you're getting the camera error - try this mod https://www.nexusmods.com/battlebrothers/mods/159

if you're getting a crash on undead/necromancer turns use the following patch
[zzz_mod_Official_Legends_patch_v4.zip](https://github.com/user-attachments/files/16174445/zzz_mod_Official_Legends_patch_v4.zip)

**Comment by BreakyZ** [comment]
whoever is experiencing the camera error:

open your legends mod zip

delete scripts/camera/ folder
