### ISSUE TITLE
[BUG] Undead Encounters are Broken

### ISSUE THREAD

**Issue by Honestly101** [Battle-Brothers-Legends/Legends-Bugs#192]
**Versions**
 - Game: 1.5.0.15
 - Chickens & Demons 18.2.7

**Describe the bug**
Undead battles cause freezes during and when attempting to load the battles. Might have something to do with necromancers and geists.

**Steps to reproduce the behavior:**
1. Go to 'roaming undead or ruin/graveyard that spawn them'
2. Click on 'either'
3. Game will either just completely freeze at the loading screen or during the battle

**Comment by zaxtin123** [comment]
damn it i think its just me the biggest problem here Undead start appearing more frequently in endgame so you need to fight them with this problem we cant play the game except running away and i dant yo run away damn it

**Comment by JuuzouXIII-gif** [comment]
Yeah they're totally bugged sadly. My 200 day first campaign came to an end when the undead endgame showed up xD

**Comment by Silica-Pathways** [comment]
Bug has been there for half a year, better get used to it.

**Comment by Silica-Pathways** [comment]
@Honestly101 , if you made a fix for the problem, please share it with us, since devs have not updated anything on GitHub.

**Comment by JuuzouXIII-gif** [comment]
I can confirm issue has been fixed. They've shared it in the legends discord... i have no idea how to invite people to it. I went there as a last resort lol but it had the golden ticket!

**Comment by Silica-Pathways** [comment]
> I can confirm issue has been fixed. They've shared it in the legends discord... i have no idea how to invite people to it. I went there as a last resort lol but it had the golden ticket!

Would be better to post the fix on GitHub though, there are many people who don't use Discord, me included.

**Comment by cajstephens** [comment]
> > I can confirm issue has been fixed. They've shared it in the legends discord... i have no idea how to invite people to it. I went there as a last resort lol but it had the golden ticket!
> 
> Would be better to post the fix on GitHub though, there are many people who don't use Discord, me included.

The discord had a patch for Legends 18.2.7. I've tested in (briefly), and was able to load a battle with undead.

[zzz_mod_Official_Legends_patch_v4.zip](https://github.com/user-attachments/files/16074218/zzz_mod_Official_Legends_patch_v4.zip)

**Comment by Silica-Pathways** [comment]
> > > I can confirm issue has been fixed. They've shared it in the legends discord... i have no idea how to invite people to it. I went there as a last resort lol but it had the golden ticket!
> > 
> > 
> > Would be better to post the fix on GitHub though, there are many people who don't use Discord, me included.
> 
> The discord had a patch for Legends 18.2.7. I've tested in (briefly), and was able to load a battle with undead.
> 
> [zzz_mod_Official_Legends_patch_v4.zip](https://github.com/user-attachments/files/16074218/zzz_mod_Official_Legends_patch_v4.zip)
> 
> Edit: Tested in multiple battles, including old and new campaigns, and can load battles against geists, necromancers, and wiedergangers. Seems to be working fine.

Thanks!

**Comment by zaxtin123** [comment]
> > > I can confirm issue has been fixed. They've shared it in the legends discord... i have no idea how to invite people to it. I went there as a last resort lol but it had the golden ticket!
> > 
> > 
> > Would be better to post the fix on GitHub though, there are many people who don't use Discord, me included.
> 
> The discord had a patch for Legends 18.2.7. I've tested in (briefly), and was able to load a battle with undead.
> 
> [zzz_mod_Official_Legends_patch_v4.zip](https://github.com/user-attachments/files/16074218/zzz_mod_Official_Legends_patch_v4.zip)
> 
> Edit: Tested in multiple battles, including old and new campaigns, and can load battles against geists, necromancers, and wiedergangers. Seems to be working fine.

thx bro
