### ISSUE TITLE
game won't start since update[BUG]

### ISSUE THREAD

**Issue by Beaghan** [Battle-Brothers-Legends/Legends-Bugs#195]
* **Versions**
 Game: [e.g. 1.4.0.49]
 Legends [e.g. 18.2.7]

* **Describe the bug**
I tried update the Legends mod and I get this fatal error. I tried uninstalling this and other mods and received even more errors after reinstalling. I tried uninstalling the game and doing a fresh reload of everything. I'm not great with computer stuff so maybe I did something wrong but I had Legends mod working fine for years through several updates and never had an issue until now.

* **Your log**
Battle Brothers 1.5.0.15
11:49:54Platform
Setting video mode
11:49:55Platform
Finished setting video mode
11:49:55Core
Using write path: C:\Users\zacka\OneDrive\Documents\Battle Brothers
11:49:55Core
Initializing Resource Manager
11:49:55Core
Initializing Input Manager
11:49:55Core
Initializing Render Manager
11:49:55Renderer
Allocated Renderbuffer in excess of 3072kb.
11:49:55Renderer
Vendor: NVIDIA Corporation
11:49:55Renderer
Device: NVIDIA GeForce RTX 3090/PCIe/SSE2
11:49:55Renderer
Version: 4.6.0 NVIDIA 536.99
11:49:55Renderer
Shader Version: 4.60 NVIDIA
11:49:55Renderer
Framebuffer Support: Yes
11:49:55Core
Initializing Sound Manager
11:49:55Core
Initializing Scene Manager
11:49:55Resource
Unloading: shaders/solid.vs
11:49:55Resource
Unloading: shaders/solid_pass0.fs
11:49:55Resource
Unloading: shaders/simple.vs
11:49:55Resource
Unloading: shaders/simple.fs
11:49:55Resource
Unloading: shaders/sprite.vs
11:49:55Resource
Unloading: shaders/sprite.fs
11:49:55Resource
Unloading: shaders/sprite_dof.vs
11:49:55Resource
Unloading: shaders/sprite_dof.fs
11:49:55Core
Initializing Script Manager
11:49:55Core
Initializing UI Manager
11:49:55Resource
Unloading: shaders/ui.vs
11:49:55Resource
Unloading: shaders/ui.fs
11:49:55Core
Initializing Input Action Manager
11:49:55Core
Initializing State Manager
11:49:55Core
Initializing Persistence Manager
11:49:55Resource
Unloading: brushes/debug.brush
11:49:55Resource
Unloading: brushes/detail.brush
11:49:55Resource
Unloading: brushes/effects_0.brush
11:49:55Resource
Unloading: brushes/entity_0.brush
11:49:55Resource
Unloading: brushes/entity_1.brush
11:49:55Resource
Unloading: brushes/entity_2.brush
11:49:55Resource
Unloading: brushes/entity_3.brush
11:49:55Resource
Unloading: brushes/entity_4.brush
11:49:55Resource
Unloading: brushes/entity_5.brush
11:49:55Resource
Unloading: brushes/entity_6.brush
11:49:55Resource
Unloading: brushes/entity_7.brush
11:49:55Resource
Unloading: brushes/entity_blood.brush
11:49:55Resource
Unloading: brushes/entity_icons.brush
11:49:55Resource
Unloading: brushes/forbiddenknowledge.brush
11:49:55Resource
Unloading: brushes/legend_armor_0.brush
11:49:55Resource
Unloading: brushes/legend_armor_1.brush
11:49:55Resource
Unloading: brushes/legend_armor_2.brush
11:49:55Resource
Unloading: brushes/legend_armor_3.brush
11:49:55Resource
Unloading: brushes/legend_armor_4.brush
11:49:55Resource
Unloading: brushes/legend_characters.brush
11:49:55Resource
Unloading: brushes/legend_detail.brush
11:49:55Resource
Unloading: brushes/legend_enemies.brush
11:49:55Resource
Unloading: brushes/legend_helmets.brush
11:49:55Resource
Unloading: brushes/legend_helmets_0.brush
11:49:55Resource
Unloading: brushes/legend_helmets_1.brush
11:49:55Resource
Unloading: brushes/legend_helmets_10.brush
11:49:55Resource
Unloading: brushes/legend_helmets_11.brush
11:49:55Resource
Unloading: brushes/legend_helmets_12.brush
11:49:55Resource
Unloading: brushes/legend_helmets_13.brush
11:49:55Resource
Unloading: brushes/legend_helmets_14.brush
11:49:55Resource
Unloading: brushes/legend_helmets_15.brush
11:49:55Resource
Unloading: brushes/legend_helmets_2.brush
11:49:55Resource
Unloading: brushes/legend_helmets_3.brush
11:49:55Resource
Unloading: brushes/legend_helmets_4.brush
11:49:55Resource
Unloading: brushes/legend_helmets_5.brush
11:49:55Resource
Unloading: brushes/legend_helmets_6.brush
11:49:55Resource
Unloading: brushes/legend_helmets_7.brush
11:49:55Resource
Unloading: brushes/legend_helmets_8.brush
11:49:55Resource
Unloading: brushes/legend_helmets_9.brush
11:49:55Resource
Unloading: brushes/legend_horses.brush
11:49:55Resource
Unloading: brushes/legend_objects.brush
11:49:55Resource
Unloading: brushes/legend_weapons.brush
11:49:55Resource
Unloading: brushes/legend_world.brush
11:49:55Resource
Unloading: brushes/mod_legendary_ghost_boss_location.brush
11:49:55Resource
Unloading: brushes/object_0.brush
11:49:55Resource
Unloading: brushes/object_1.brush
11:49:55Resource
Unloading: brushes/orientation.brush
11:49:55Resource
Unloading: brushes/orientation_overlay.brush
11:49:55Resource
Unloading: brushes/terrain.brush
11:49:55Resource
Unloading: brushes/transitions.brush
11:49:55Resource
Unloading: brushes/ui.brush
11:49:55Resource
Unloading: brushes/world.brush
11:49:55Resource
Unloading: brushes/world_decals.brush
11:49:55Resource
Unloading: brushes/world_detail.brush
11:49:55Resource
Unloading: brushes/world_detail_1.brush
11:49:55Resource
Unloading: brushes/world_entity_0.brush
11:49:55Resource
Unloading: brushes/world_settlement.brush
11:49:55Resource
Unloading: brushes/world_special.brush
11:49:55Resource
Unloading: brushes/world_tiles.brush
11:49:55Resource
Unloading: brushes/world_weather.brush
11:49:55IO
Unexpected file or directory found: brekiy_lots_o_names-659-1-1-0-1691535046.zip
11:49:55IO
Unexpected file or directory found: bro_studio_1.0.2.zip-677-1-0-2-1697941124.zip
11:49:55IO
Unexpected file or directory found: modz_AC_126_Legends_125-371-125-1627152036.zip
11:49:55IO
Unexpected file or directory found: mod_dog_love-686-1-2-0-1704922459.zip
11:49:55IO
Unexpected file or directory found: mod_forbidden_knowledge_1.1.2-698-1-1-2-1708756899.zip
11:49:55IO
Unexpected file or directory found: mod_heal_repair_fix_0.6.zip-668-0-6-1700543256.zip
11:49:55IO
Unexpected file or directory found: mod_hooks.zip-42-21-1621705200.zip
11:49:55IO
Unexpected file or directory found: mod_legendary_kriegsgeist_location_legends-582-1-0-5-1660660122.zip
11:49:55IO
Unexpected file or directory found: mod_Legends_Chickens_and_Demons_18.2.7.zip
11:49:55IO
Unexpected file or directory found: mod_legends_favoured_enemy_refund_2.0.1-622-2-0-1-1681148815.zip
11:49:55IO
Unexpected file or directory found: mod_modern_hooks-685-0-5-1-1719344094.2.zip
11:49:55IO
Unexpected file or directory found: mod_msu-479-1-2-7-1695155944.zip
11:49:55IO
Unexpected file or directory found: mod_msu-479-1-3-0-1719216874.1.zip
11:49:55IO
Unexpected file or directory found: mod_msu-479-1-3-0-1719216874.zip
11:49:55IO
Unexpected file or directory found: mod_retinue_ups_0.7.zip-681-0-7-1702274548.zip
11:49:55IO
Unexpected file or directory found: stdlib_1.7.zip-676-1-7-1701491397.zip
11:49:55IO
Unexpected file or directory found: vortex.deployment.json
11:49:55IO
Unexpected file or directory found: Word's Slayer Perks-637-1-0-1684192889.zip
11:49:55IO
Unexpected file or directory found: zzz_mod_Official_Legends_patch_v4.zip
11:49:55IO
Unexpected file or directory found: zzz_mod_zzz_delz_houndmasterbgplus111-382-1-111-1627204903.zip
11:49:55IO
The game uses modified files or files that are not part of the official release. If you encounter any issues, please first remove any mods and try again before contacting support.
11:49:55Resource
Unloading: shaders/fow.vs
11:49:55Resource
Unloading: shaders/fow.fs
11:49:55Texture
Texture "gfx/fow.png" (ID: 5) took up approximately 16384kb in video memory.
11:49:55Resource
Unloading: shaders/water.vs
11:49:55Resource
Unloading: shaders/water.fs
11:49:55Texture
Texture "gfx/water.png" (ID: 6) took up approximately 16384kb in video memory.
11:49:55Texture
Texture "gfx/world_tiles.png" (ID: 7) took up approximately 43680kb in video memory.
11:49:55Texture
Texture "gfx/world_special.png" (ID: 8) took up approximately 256kb in video memory.
11:49:55Texture
Texture "gfx/terrain.png" (ID: 9) took up approximately 10912kb in video memory.
11:49:55Texture
Texture "gfx/transitions.png" (ID: 10) took up approximately 5456kb in video memory.
11:49:55Resource
Parsed Resource Package "preload/on_start.txt" with 5 items.
11:49:55Resource
Started loading Resource Package "preload/on_start.txt".
11:49:55Texture
Compressed texture "gfx/effects_0.png" from 16384kb to 4096kb.
11:49:56Texture
Compressed texture "gfx/world_weather.png" from 32768kb to 8192kb.
11:49:56Texture
Texture "gfx/ui.png" (ID: 13) took up approximately 10922kb in video memory.
11:49:56Texture
Texture "gfx/fonts/cinzel_bold_20.png" (ID: 14) took up approximately 512kb in video memory.
11:49:56Texture
Texture "gfx/fonts/cinzel_bold_100.png" (ID: 15) took up approximately 8192kb in video memory.
11:49:56SQ
=================Initialized Hooks=================
11:49:56SQ
mod_hooks: Redirecting core functions
11:49:56SQ
mod_hooks: mod_hooks (modding script hooks) version 21.1 registered.
11:49:56SQ
=================Patching Modding Script Hooks=================
11:49:56SQ
Modern Hooks registered modding script hooks (mod_hooks) version 21.1
11:49:56SQ
Modern Hooks registered Legends Mod (mod_legends) version 18.2.7
11:49:56SQ
Modern Hooks registered stdlib (stdlib) version 1.7
11:49:56SQ
Modern Hooks registered Accessory Companions (mod_AC) version 1.26
11:49:56SQ
Modern Hooks registered ModJimmysTooltips (mod_Jimmys_Tooltips) version 1.0.5
11:49:56SQ
Modern Hooks registered Bro Studio (mod_bro_studio) version 1.0.2
11:49:56SQ
Modern Hooks registered More Love For Dogs (mod_dog_love) version 1.2.0
11:49:56SQ
Modern Hooks registered Events and Ambitions Delayed Fix (mod_events_delayed_fix) version 0.7
11:49:56SQ
Modern Hooks registered Dragonslayerelf's Forbidden Knowledge Origin (mod_dseForbiddenKnowledgeOrigin) version 1.1.2
11:49:56SQ
Modern Hooks registered Cool and Blacksmith Fix (mod_heal_repair_fix) version 0.6
11:49:56SQ
Modern Hooks registered Legends Favoured Enemy Perk Point Refund (mod_legends_favoured_enemy_refund) version 2.0.1
11:49:56SQ
Modern Hooks registered Lots O' Names (mod_lots_o_names) version 1
11:49:56SQ
Modern Hooks registered Vanilla (vanilla) version 1.5.0-15
11:49:56SQ
Modern Hooks registered dlc_unhold_supporter (dlc_unhold_supporter) version 1.0.0
11:49:56SQ
Modern Hooks registered DLC: Beasts & Exploration (dlc_unhold) version 1.0.0
11:49:56SQ
Modern Hooks registered dlc_wildmen_supporter (dlc_wildmen_supporter) version 1.0.0
11:49:56SQ
Modern Hooks registered DLC: Lindwurm (dlc_lindwurm) version 1.0.0
11:49:56SQ
Modern Hooks registered dlc_desert_supporter (dlc_desert_supporter) version 1.0.0
11:49:56SQ
Modern Hooks registered DLC: Of Flesh and Faith (dlc_paladins) version 1.0.0
11:49:56SQ
Modern Hooks registered dlc_fangshire (dlc_fangshire) version 1.0.0
11:49:56SQ
Modern Hooks registered DLC: Blazing Deserts (dlc_desert) version 1.0.0
11:49:56SQ
Modern Hooks registered DLC: Warriors of the North (dlc_wildmen) version 1.0.0
11:49:56SQ
Modern Hooks registered Modern Hooks (mod_modern_hooks) version 0.5.1
11:49:56SQ
Modern Hooks registered Retinue Promotions (mod_retinue_ups) version 0.7
11:49:56SQ
Modern Hooks registered Word's Slayer Perks (mod_WordsSlayerPerks) version 1.3
11:49:56SQ
Modern Hooks registered Modding Standards & Utilities (MSU) (mod_msu) version 1.3.0
11:49:56SQ
Modern Hooks registered Legendary Kriegsgeist Location (mod_legendary_kriegsgeist_boss_location) version 1.0.5
11:49:56SQ
Modern Hooks registered Close Combat Archer Tooltip (mod_close_combat_archer_tooltip) version 2
11:49:56SQ
=================Running Queue=================
11:49:56SQ
-----------------Running queue bucket First-----------------
11:49:56SQ
Executing queued function 1 for Modern Hooks (mod_modern_hooks) version 0.5.1.
11:49:56SQ
Executing queued function 2 for Modding Standards & Utilities (MSU) (mod_msu) version 1.3.0.
11:49:56SQ
-----------------Running queue bucket Normal-----------------
11:49:56SQ
Executing queued function 1 for Modding Standards & Utilities (MSU) (mod_msu) version 1.3.0.
11:49:56SQ
MSU registered Modding Standards & Utilities (MSU), version: 1.3.0
11:49:56SQ
MSU registered Vanilla (MSU), version: 1.5.0-15
11:49:56SQ
Executing queued function 1 for Accessory Companions (mod_AC) version 1.26.
11:49:56SQ
Executing queued function 1 [After: mod_hooks] for Events and Ambitions Delayed Fix (mod_events_delayed_fix) version 0.7.
11:49:56SQ
Executing queued function 1 [After: mod_hooks] for Cool and Blacksmith Fix (mod_heal_repair_fix) version 0.6.
11:49:56SQ
Executing queued function 1 for Lots O' Names (mod_lots_o_names) version 1.
11:49:56SQ
Executing queued function 1 [After: mod_hooks, sato_balance_mod, tnf_expandedRetinue, mod_more_followers] for Retinue Promotions (mod_retinue_ups) version 0.7.
11:49:56SQ
Executing queued function 1 [After: mod_msu, vanilla, dlc_lindwurm, dlc_unhold, dlc_wildmen, dlc_desert, dlc_paladins] for Legends Mod (mod_legends) version 18.2.7.
11:49:56SQ
MSU registered Legends Mod, version: 18.2.7
11:49:56SQ
Executing queued function 1 [After: stdlib, mod_hooks, mod_msu] for Bro Studio (mod_bro_studio) version 1.0.2.
11:49:56SQ
MSU registered Bro Studio, version: 1.0.2
11:49:56SQ
Executing queued function 1 [After: mod_msu] for More Love For Dogs (mod_dog_love) version 1.2.0.
11:49:56SQ
Mod mod_msu (Modding Standards & Utilities (MSU)) is wrapping function isType in bb class scripts/skills/skill with a different number of parameters, but the additional parameters are optional, so this is probably fine (used to be 1, wrapper returned function with 3)
11:49:56SQ
Executing queued function 3 [After: mod_msu] for Modern Hooks (mod_modern_hooks) version 0.5.1.
11:49:56SQ
MSU registered Modern Hooks, version: 0.5.1
11:49:56SQ
Executing queued function 1 [After: mod_legends, mod_msu] for ModJimmysTooltips (mod_Jimmys_Tooltips) version 1.0.5.
11:49:56SQ
MSU registered ModJimmysTooltips, version: 1.0.5
11:49:56SQ
Executing queued function 1 [After: mod_legends, mod_msu] for Dragonslayerelf's Forbidden Knowledge Origin (mod_dseForbiddenKnowledgeOrigin) version 1.1.2.
11:49:56SQ
MSU registered Dragonslayerelf's Forbidden Knowledge Origin, version: 1.1.2
11:49:56SQ
Executing queued function 1 [After: mod_msu, mod_legends] for Legends Favoured Enemy Perk Point Refund (mod_legends_favoured_enemy_refund) version 2.0.1.
11:49:56SQ
MSU registered Legends Favoured Enemy Perk Point Refund, version: 2.0.1
11:49:56SQ
Executing queued function 1 [After: mod_legends, mod_msu] for Word's Slayer Perks (mod_WordsSlayerPerks) version 1.3.
11:49:56SQ
Executing queued function 1 [After: mod_legends] for Legendary Kriegsgeist Location (mod_legendary_kriegsgeist_boss_location) version 1.0.5.
11:49:56SQ
MSU registered Legendary Kriegsgeist Location, version: 1.0.5
11:49:56SQ
Executing queued function 1 [After: mod_legends, mod_msu] for Close Combat Archer Tooltip (mod_close_combat_archer_tooltip) version 2.
11:49:56SQ
-----------------Running queue bucket VeryLate-----------------
11:49:56SQ
Executing queued function 3 for Modding Standards & Utilities (MSU) (mod_msu) version 1.3.0.
11:49:56SQ
-----------------Running queue bucket Last-----------------
11:49:56SQ
Executing queued function 2 for Modern Hooks (mod_modern_hooks) version 0.5.1.
11:49:57SQ
Mod mod_msu (Modding Standards & Utilities (MSU)) is wrapping function isItemType in bb class scripts/items/item with a different number of parameters, but the additional parameters are optional, so this is probably fine (used to be 1, wrapper returned function with 3)
11:49:58Script Error
the index 'onUpdate' does not exist
Function:
-> mod_legends_favoured_enemy_refund/hooks/skills/perks/perk_legend_favoured_enemy_master_archer.nut : 8
Variables:
o = Table, this = Table
Function:
call -> NATIVE : -1
Function:
-> modern_hooks/private_globals.nut : 360
Variables:
hookInfo = Table, @INDEX@ = 0, root = Table, p = Table, _src = scripts/skills/perks/perk_legend_favoured_enemy_master_archer, this = Table
Function:
-> modern_hooks/private_globals.nut : 411
Variables:
bbclass = Table, src = scripts/skills/perks/perk_legend_favoured_enemy_master_archer, root = Table, this = Table
Function:
main -> scripts/~~modern_hooks.nut : 3
Variables:
vargv = Array, this = Table
Function:
unknown -> NATIVE : -1
Function:
main -> scripts/preload.nut : 62
Variables:
@ITERATOR@ = 5544, scriptFile = scripts/~~modern_hooks, @INDEX@ = 5543, scriptFiles = Array, dlcInitScriptFiles = Array, configScriptFiles = Array, priorityScriptFiles = Array, scriptsDLCInitPath = scripts/dlc/, scriptsConfigPath = scripts/config/, scriptsPath = scripts/, gt = Table, vargv = Array, this = Table
11:49:58SQ
Mod mod_hooks (modding script hooks) version 21.1 had an error (the index 'onUpdate' does not exist) during its hook on bb class scripts/skills/perks/perk_legend_favoured_enemy_master_archer.
11:49:58SQ
Raise Undead hook loaded.
11:49:58SQ
-----------------Running queue bucket AfterHooks-----------------
11:49:58SQ
Executing queued function 4 for Modding Standards & Utilities (MSU) (mod_msu) version 1.3.0.
11:49:58SQ
=================Finalized Hooks=================
11:49:58UI
Screen 'ModernHooksConnection' successfully registered.
11:49:58UI
Screen 'RootScreen' successfully registered.
11:49:59SQ
RootState::onShow()
11:49:59Resource
Parsed Resource Package "preload/on_running.txt" with 69 items.
11:49:59Resource
Started loading Resource Package "preload/on_running.txt".
11:49:59Texture
Texture "gfx/entity_blood.png" (ID: 16) took up approximately 5461kb in video memory.
11:49:59Texture
Texture "gfx/legend_characters.png" (ID: 18) took up approximately 21845kb in video memory.
11:49:59UI
Screen 'MSUPopup' successfully registered.
11:49:59UI
Screen 'MSUConnection' successfully registered.
11:49:59UI
Screen 'ModSettingsScreen' successfully registered.
11:49:59UI
Screen 'ConsoleScreen' successfully registered.
11:49:59UI
Screen 'LoadingScreen' successfully registered.
11:49:59UI
Screen 'TooltipScreen' successfully registered.
11:49:59UI
Screen 'DialogScreen' successfully registered.
11:49:59UI
Screen 'TacticalScreen' successfully registered.
11:49:59UI
Screen 'TacticalCombatResultScreen' successfully registered.
11:49:59UI
Screen 'TacticalDialogScreen' successfully registered.
11:49:59UI
Screen 'WorldScreen' successfully registered.
11:49:59UI
Screen 'WorldTownScreen' successfully registered.
11:49:59UI
Screen 'WorldGameFinishScreen' successfully registered.
11:49:59UI
Screen 'WorldEventPopupScreen' successfully registered.
11:49:59UI
Screen 'WorldEventScreen' successfully registered.
11:49:59UI
Screen 'WorldCombatDialog' successfully registered.
11:49:59UI
Screen 'WorldRelationsScreen' successfully registered.
11:49:59UI
Screen 'WorldObituaryScreen' successfully registered.
11:49:59UI
Screen 'WorldCampfireScreen' successfully registered.
11:49:59UI
Screen 'MainMenuScreen' successfully registered.
11:49:59UI
Screen 'WorldMenuScreen' successfully registered.
11:49:59UI
Screen 'TacticalMenuScreen' successfully registered.
11:49:59UI
Screen 'WorldCharacterScreen' successfully registered.
11:49:59UI
Screen 'TacticalCharacterScreen' successfully registered.
11:49:59Persistence
Unable to read meta data from "savegames/steam_autocloud.vdf" because magic number does not match.
11:49:59Texture
Texture "gfx/legend_world.png" (ID: 21) took up approximately 87381kb in video memory.
11:50:00Texture
Texture "gfx/legend_weapons.png" (ID: 25) took up approximately 43690kb in video memory.
11:50:00UI
Screen 'CampScreen' successfully registered.
11:50:00Texture
Texture "gfx/legend_armor_0.png" (ID: 46) took up approximately 21845kb in video memory.
11:50:00Texture
Texture "gfx/legend_armor_1.png" (ID: 55) took up approximately 21845kb in video memory.
11:50:00Texture
Texture "gfx/legend_armor_2.png" (ID: 56) took up approximately 43690kb in video memory.
11:50:00Texture
Texture "gfx/legend_armor_3.png" (ID: 57) took up approximately 43690kb in video memory.
11:50:00Texture
Texture "gfx/legend_armor_4.png" (ID: 58) took up approximately 1365kb in video memory.
11:50:00Texture
Texture "gfx/legend_enemies.png" (ID: 59) took up approximately 21845kb in video memory.
11:50:00Texture
Texture "gfx/legend_helmets.png" (ID: 60) took up approximately 21845kb in video memory.
11:50:00Texture
Texture "gfx/legend_helmets_0.png" (ID: 61) took up approximately 21845kb in video memory.
11:50:00Texture
Texture "gfx/legend_helmets_1.png" (ID: 62) took up approximately 21845kb in video memory.
11:50:00Texture
Texture "gfx/legend_helmets_2.png" (ID: 63) took up approximately 21845kb in video memory.
11:50:00Texture
Texture "gfx/legend_helmets_3.png" (ID: 64) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_4.png" (ID: 65) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_5.png" (ID: 66) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_6.png" (ID: 67) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_7.png" (ID: 68) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_8.png" (ID: 69) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_9.png" (ID: 70) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_10.png" (ID: 71) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_11.png" (ID: 72) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_12.png" (ID: 73) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_13.png" (ID: 74) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_14.png" (ID: 75) took up approximately 21845kb in video memory.
11:50:01Texture
Texture "gfx/legend_helmets_15.png" (ID: 76) took up approximately 5461kb in video memory.
11:50:01Texture
Texture "gfx/legend_horses.png" (ID: 77) took up approximately 10922kb in video memory.
11:50:01Texture
Texture "gfx/legend_objects.png" (ID: 78) took up approximately 10922kb in video memory.
11:50:02Texture
Texture "gfx/entity_0.png" (ID: 79) took up approximately 43690kb in video memory.
11:50:02Texture
Texture "gfx/entity_3.png" (ID: 80) took up approximately 10922kb in video memory.
11:50:02Texture
Texture "gfx/entity_icons.png" (ID: 81) took up approximately 43690kb in video memory.
11:50:02Texture
Texture "gfx/world_detail.png" (ID: 82) took up approximately 43690kb in video memory.
11:50:02Texture
Texture "gfx/world_entity_0.png" (ID: 83) took up approximately 21845kb in video memory.
11:50:02Texture
Texture "gfx/world_settlement.png" (ID: 84) took up approximately 43690kb in video memory.
11:50:02Texture
Texture "gfx/world_decals.png" (ID: 85) took up approximately 10920kb in video memory.
11:50:50Core
Shutting down engine core.

**YOUR BUG REPORT IS NOT HELPFUL WITHOUT THE LOG, SO PLEASE UPLOAD IT**
* **To Reproduce**
click play, game starts loading/running and error pops up

* **Screenshots**

![20240713121554_1](https://github.com/user-attachments/assets/ee0aebe9-34ed-48c1-b75d-59a01be5aed4)
 

* **Additional context**

thank you for any assistance with this.

**Comment by BreakyZ** [comment]
are you able to come on the official discord?

**Comment by Beaghan** [comment]
> are you able to come on the official discord?

Sure, should I do the same post there or is there a solution there?

**Comment by BreakyZ** [comment]
Post a bug report in the bug reports channel, your mod list needs some work to have a stable experience and it's annoying to do on github.
