### ISSUE TITLE
[BUG] HUGE problem with undead and Necromancer at 18.2.7 (Chickens and Demons)

### ISSUE THREAD

**Issue by Miron1551** [Battle-Brothers-Legends/Legends-Bugs#196]
* **Versions**
 Game: [1.4.0.49]
 Legends [18.2.7]
Steam version with mods (print screen with mods attached)
![Mods](https://github.com/user-attachments/assets/6e829d6d-0573-4fde-9203-ff6600be2147)

* **Describe the bug**
There is HUGE problem with undead and Necromancer!
Every time Necromancer summoning undead they simply do not appear and fight stops.
Could you please check this [out.](url)

* **Your log**
Uploaded

**YOUR BUG REPORT IS NOT HELPFUL WITHOUT THE LOG, SO PLEASE UPLOAD IT**
* **To Reproduce**
Fight in autosave until undead summoned by Necromancer

* **Screenshots**
On screenshot nothing will be visible, because undead are invisible 

* **Additional context**
[Undead problem.zip](https://github.com/user-attachments/files/16203471/Undead.problem.zip)

**Comment by zaxtin123** [comment]
use this lil buddy

[zzz_mod_Official_Legends_patch_v4.zip](https://github.com/user-attachments/files/16216015/zzz_mod_Official_Legends_patch_v4.zip)

**Comment by BreakyZ** [comment]
dl patch above and replace faster with swifter as it's known to cause issues

**Comment by Miron1551** [comment]
> dl patch above and replace faster with swifter as it's known to cause issues

Could you please tell where to download ?

**Comment by Miron1551** [comment]
> use this lil buddy
> 
> [zzz_mod_Official_Legends_patch_v4.zip](https://github.com/user-attachments/files/16216015/zzz_mod_Official_Legends_patch_v4.zip)

Thanks will try now
