### ISSUE TITLE
[BUG] CTD when fighting undead (yes, with the fix)

### ISSUE THREAD

**Issue by Silica-Pathways** [Battle-Brothers-Legends/Legends-Bugs#198]
* **Versions**
Game: 1.5.0.15 (Steam)
Legends 18.2.7 (with fix)

* **Describe the bug**
CTD in fight against undead

Not sure, not even sure how oft it would repeat, since log text give no clear idea what happened. BUT:
* Before starting new campaign, I got the MSU update today (1.4.1) too (is it buggy?).
* I am playing Inquisitor origin (meaning, the automatic undead crisis from beginning).

[
![ce](https://github.com/user-attachments/assets/43966f58-40dc-478c-a1e6-5283223b9867)
](url)

[log.zip](https://github.com/user-attachments/files/16231115/log.zip)

**Comment by BreakyZ** [comment]
Has the ai been able to use rotation previously btw? Else this will remove ai rotation and you should not experience this problem again. 
[mod_disable_rotation_behavouir.zip](https://github.com/user-attachments/files/16233182/mod_disable_rotation_behavouir.zip)

**Comment by Silica-Pathways** [comment]
I didn't use your fix (since the bug is rare and I don't want to inhibit AI too much). had same CTD when fighting barbarians:
![ce](https://github.com/user-attachments/assets/7b03ea26-d043-4076-9f66-6fc717109c04)
[log.zip](https://github.com/user-attachments/files/16388999/log.zip)

**Comment by BreakyZ** [comment]
do you have the kick skill on any of your bros by any chance?

**Comment by Silica-Pathways** [comment]
> do you have the kick skill on any of your bros by any chance?

No, that's quite early game, we barely have any perks (4 total, afaik).

**Comment by BreakyZ** [comment]
We did a pretty exhaustive refactor of the ai so hopefully these things will be fixed next build
