### ISSUE TITLE
[BUG] Wrong icon in spiked coif description tooltip

### ISSUE THREAD

**Issue by Silica-Pathways** [Battle-Brothers-Legends/Legends-Bugs#199]
Versions
Game: 1.5.0.15 (Steam)
Legends 18.2.7 (with fix)

* **Describe the bug**
Spiked coif description says "initiative", yet shows resolve icon next the word.

* **To Reproduce**
1. Get spiked coif (oath takers seem to have it from the beginning)
2. Mouse over for the tool tip.

I won't bother a log, since this bug seems easy to repeat.

![20240720122223_1](https://github.com/user-attachments/assets/12988cf0-25c2-4a3a-a850-c3372d02b151)

**Comment by BreakyZ** [comment]
Thank you. Will be fixed next build.
