### ISSUE TITLE
[BUG] Decription of the skill "Danger Pay" is missing a lot of information

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#20]
**Versions**
 - Game: 1.4.0.49
 - Legends 15.0.1.17c

**Describe the bug**
The perk **Danger Pay** grants a skill to the brother. This skill has almost no description as shown in the screenshot.

**Screenshots**
![DangerPayMissingDescription](https://user-images.githubusercontent.com/2252464/128057312-501352ec-f330-42bb-9873-4a6559ff995f.PNG)

**Comment by Enduriel** [comment]
I believe this was fixed with .21 or .20 and I just forgot about it.
