### ISSUE TITLE
[BUG] Children's Crusade script error

### ISSUE THREAD

**Issue by Silica-Pathways** [Battle-Brothers-Legends/Legends-Bugs#200]
Versions
Game: 1.5.0.15 (Steam)
Legends 18.2.7 (with fix)

Children's Crusade event has a script error (so log says) when choosing the 'north experienced' character to talk to the kids, it results with a "%doubter%" in the event text, making it less sensible (see screenshot).

To Reproduce:
I have not a slightest clue what triggers Children's Crusade event, if anything at all, could be purely random event on a road.

![20240721200657_1](https://github.com/user-attachments/assets/2abb029e-5612-4141-b105-28db85717eaa)

[log.zip](https://github.com/user-attachments/files/16324733/log.zip)

**Comment by BreakyZ** [comment]
the log helped a lot, should be fixed next build

**Comment by Silica-Pathways** [comment]
> the log helped a lot, should be fixed next build

Too bad the log wasn't enough for the tavern rumor bug though. I'll post more logs of it when I see it again.
