### ISSUE TITLE
[BUG] Loading forever before fighting with Necromancer

### ISSUE THREAD

**Issue by TaihouKai** [Battle-Brothers-Legends/Legends-Bugs#201]
* **Versions**
 Game: 1.5.0.15
 Legends 18.2.7

* **Describe the bug**
Loading forever before fighting with Necromancer

* **Your log**
https://file.io/n7c3GybTDLgW

* **To Reproduce**
1. Receive a quest fighting necromancer and his monsters
2. Engage
3. Loading

* **Screenshots**
(Just stuck at the loading screen)

* **Additional context**
BroEditor (for legends) enabled

**Comment by BreakyZ** [comment]
get patch4 - it's in the latest build files

**Comment by Mcantrelle93** [comment]
Having the same issue and the patch doesn’t seem to have helped. Any ideas?

**Comment by BreakyZ** [comment]
> Having the same issue and the patch doesn’t seem to have helped. Any ideas?

post a log, you can put it in a zip

**Comment by TaihouKai** [comment]
Just FYI patch4 worked for me.
