### ISSUE TITLE
[BUG]Enemies resurrected as Wiederganger have no sprite and can't be hit, and the game doesn't continue to the next round.

### ISSUE THREAD

**Issue by TomBschmns** [Battle-Brothers-Legends/Legends-Bugs#202]
* **Versions**
 Game: 1.5.0.15
 Legends 18.2.7

* **Describe the bug**
When a bro or an enemy is killed and afterwards resurrected bij a necromancer, or in my case also the undead crisis, it comes back as an wiederganger, but without a sprite.I can see it's stats, but cannot target it directly. If I hit it with an AOE attack, the game crashes (not recorded in the log). At the end of the round where de wiederganger spawned, the game will not continue. It does noet crash, but there are no more moves i, or the enemy, can make. I presume it want's to move the wiedergangers but can't.

* **Your log**
[log.zip](https://github.com/user-attachments/files/16897675/log.zip)

* **To Reproduce**
happens everytime somebody gets resurectedas a wiederganger.

* **Screenshots**
Wiederganger is there, but has no sprite and cannot be targetted.
![20240905175309_1](https://github.com/user-attachments/assets/73f92f71-373f-4eeb-9c32-346195fc76e2)
After the round has ended it stays like this.
![20240905175428_1](https://github.com/user-attachments/assets/efb37f2b-9eae-4e85-bdb3-e501e22f6f3e)

**Comment by BreakyZ** [comment]
Sorry for the late reply. Get patch 4, it's in the release files
