### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DzhangarM** [Battle-Brothers-Legends/Legends-Bugs#203]
* **Versions**
 Game: [1.5.0.15]
 Legends [e.g. 18.2.7]

* **Describe the bug**
Critical error while loading a saved game

* **Your log**
From the log:
﻿18:15:51
Core
A critical exception occured.
18:15:51
Core
Modules & Application Stacktrace:
SymInit: Symbol-SearchPath: '.;C:\Games\Steam\steamapps\common\Battle Brothers;C:\Games\Steam\steamapps\common\Battle Brothers\win32;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'user'
OS-Version: 6.2.9200 () 0x100-0x118:15:51
Core
Script Stacktrace:
Function:
onDeserialize -> C:\Users\Austin\Desktop\bb legends repo\new_build\scripts\statistics\statistics_manager.nut : 247
Function:
onDeserialize -> C:\Users\Austin\Desktop\bb legends repo\new_build\scripts\states\world_state.nut : 4069
Function:
-> msu/hooks/states/world_state.nut : 303
Function:
unknown -> NATIVE : -1
Function:
loadCampaign -> C:\Users\Austin\Desktop\bb legends repo\new_build\scripts\states\world_state.nut : 1270
Function:
-> msu/hooks/states/world_state.nut : 193
Function:
-> msu/hooks/states/world_state.nut : 370
Function:
-> C:\Users\Austin\Desktop\bb legends repo\new_build\scripts\!mods_preload\!!redirect.nut : 353
Function:
init -> C:\Users\Austin\Desktop\bb legends repo\new_build\scripts\states\world_state.nut : 1139
Function:
onInit -> C:\Users\Austin\Desktop\bb legends repo\new_build\scripts\states\world_state.nut : 560

**YOUR BUG REPORT IS NOT HELPFUL WITHOUT THE LOG, SO PLEASE UPLOAD IT**
* **To Reproduce**
I don't know why it happens but may be save game corruption (every save in the current session of the game) occurs after quicksave. Also i'm not Austin (C:\Users\Austin), i'm User

**Comment by BreakyZ** [comment]
austin is just the dev who makes the build, no need to worry there

as for the error, it does look like save corruption, sadly you didn't post your full log so i can't check what the issue might be

if you're able to, come to our discord and drop a bug report as we can talk more freely there

**Comment by DzhangarM** [comment]
Hello, here is a log. Tried to load a save game today. Every time it happens after 50-70 days in a game. Also i noticed it happened twice in different games right after Undead Scourge crisis begins
[log.zip](https://github.com/user-attachments/files/17278009/log.zip)

**Comment by BreakyZ** [comment]
right off the bat i see some incompatible mods, you can check the link below to sort out your mods

https://docs.google.com/spreadsheets/d/1TVudYJBl65IvFnF8j8yMuU2Ij5OY9ig7kl8tYO3Waqo/edit#gid=0

the issue itself looks like save corruption, you should try the following two mods to avoid this in the future:

https://www.nexusmods.com/battlebrothers/mods/729
https://www.nexusmods.com/battlebrothers/mods/389
