### ISSUE TITLE
[BUG] MSU not detected

### ISSUE THREAD

**Issue by soneill-language-arts** [Battle-Brothers-Legends/Legends-Bugs#204]
Hello,

On starting the game the msu mod is not detected, even if other mods that require msu recognize the mod.
I tried it with different configurations of mods. modern hook is installed. I use GoG with BB. I haven't tried it with steam as I would need to buy it again. I do have all dlcs. 

Game: 1.4.0.47
Legends 18.1.1
Win 11

**Comment by BreakyZ** [comment]
go to the latest release and update to 18.2.7 + patch4

msu requires modern hooks which is not mod hooks which is packaged with legends
