### ISSUE TITLE
[BUG] C2D when loading a fight

### ISSUE THREAD

**Issue by ecahill34** [Battle-Brothers-Legends/Legends-Bugs#205]
* **Versions**
 Game: [e.g. 1.5.0.15]
 Legends [e.g. 18.2.7]

Disclaimer, I have Avast, but have added the two folder paths to file exceptions list

Mod list:
![image](https://github.com/user-attachments/assets/2c8f3ef4-f8eb-4b33-801b-78aa9641fcf6)

* **Describe the bug**
Crash to desktop when initiating a battle. Can be any battle against any foe

* **Your log**
Please post your log so we can help. 
Your log is found in: ```C:\Users\YourName\Documents\Battle Brothers\log.html```
The log is constantly updated during game and is reset each time you open the game and it is best to upload the log when the error first occurred.
[log.txt](https://github.com/user-attachments/files/17498033/log.txt)

**YOUR BUG REPORT IS NOT HELPFUL WITHOUT THE LOG, SO PLEASE UPLOAD IT**
* **To Reproduce**
1. Start a fight with any enemy, when selecting Engage, it immediately crashes and I get the error in the screenshot. The autosave is then broken. I also get some random issue where item pictures go blank

, and objects on the map show a weird colour. Will get a screen of that

* **Screenshots**
![image](https://github.com/user-attachments/assets/4d8a59a9-88fa-4649-bd7b-2a5be5c3ffdc)

* **Additional context**
Add any other context about the problem, such as links to a discord discussion, here.

**Comment by ecahill34** [comment]
Screenshot of the error when trying to load the now-corrupted autosave
![image](https://github.com/user-attachments/assets/c707d344-d0cb-4d2c-9997-aeaf05ab572f)

**Comment by ecahill34** [comment]
Screenshot of the map bug where objects are replaced with... something
![image](https://github.com/user-attachments/assets/1c4a0dff-312a-4fb5-b99e-b4a4d0c8fe1f)

**Comment by BreakyZ** [comment]
please post a proper log, zip the .log file because txt is unreadable

**Comment by BreakyZ** [comment]
your issue with initiating fights is because you don't have patch4 - it's under the 18.2.7 release files

as for the weird glitches it's what we call memory corruption, when you experience those never save your game and try using [msu launcher](https://www.nexusmods.com/battlebrothers/mods/729)

if you're on our official discord i can provide additional support

**Comment by ecahill34** [comment]
Ah I thought this was the patch, I just removed the zzz_
![image](https://github.com/user-attachments/assets/2d599dc4-3384-492b-988d-ef75bd82125f)

**Comment by BreakyZ** [comment]
i'm not sure why would you do that
