### ISSUE TITLE
[BUG] Hexen Leader Silk Cloak is unvisible

### ISSUE THREAD

**Issue by Stuart-554** [Battle-Brothers-Legends/Legends-Bugs#206]
* **Versions**
 Game: [e.g. 1.5.0.15]
 Legends [e.g. 18.2.7]

* **Describe the bug**
First thing first, after I crafted the item, it showed on it's icon that it's a layer 4 armor, but under the "IV" there was "+" symbol, like it is an upgrade attachment for layer 5. But it's actually unrelated to the issue and the item works just fine, attaching to layer 4, and no issues with stats and effects. It's just that, after I reboot the game it becomes forever unvisible, both in inventory and on character model. I am pretty sad, it looked very cool though...

* **Your log**

[log.zip](https://github.com/user-attachments/files/17506193/log.zip)

**Comment by Stuart-554** [comment]
I guess, there is a lot of issues, with craftable cloaks and other craftable attachments, from what I've seen from other players.

**Comment by chopeks** [comment]
fixed in 19.0.0
