### ISSUE TITLE
[BUG] Game crashes when trying to save after leaving the city

### ISSUE THREAD

**Issue by Shr1xy** [Battle-Brothers-Legends/Legends-Bugs#207]
* **Versions**
 Game: [1.5.0.15]
 Legends [18.2.7]

* **Describe the bug**
Game crashes when trying to save after leaving the city

* **Your log**
attached screenshots 
![Screenshot_1](https://github.com/user-attachments/assets/7ad674e1-425b-4eb9-9862-d1cdb17c92d4)
![Screenshot_2](https://github.com/user-attachments/assets/ebb65d03-64d1-426c-b6c8-e604b40b6e67)
![Screenshot_3](https://github.com/user-attachments/assets/dbb4de6c-847a-4791-9bb2-39a03937bf85)
![Screenshot_4](https://github.com/user-attachments/assets/98bda4a9-944d-4cad-871c-b5bd220ae877)
![Screenshot_5](https://github.com/user-attachments/assets/cd17409e-a06a-48d0-9dd4-bcab87926098)

**Comment by Shr1xy** [comment]
Added full log
[log.zip](https://github.com/user-attachments/files/17650523/log.zip)

**Comment by BreakyZ** [comment]
I think the following mods:

mod_sr_alternative
ContractColors
settlementSituationTooltipsALL - this has a replacement - settlement tooltips msu on nexus

otherwise this looks like savegame corruption, you can try getting the mods "more save slots" and "msu launcher" from nexus, if this doesn't work and you can make it onto the legends discord I can provide additional help

**Comment by Shr1xy** [comment]
Thank you for your reply!
I will delete these mods and try to load auto save. Or I should start new company without any mods (exept legendary, msu, and hooks)?

**Comment by BreakyZ** [comment]
try to load your save, as i said if you come on the legends discord i can maybe help you continue your current campaign

**Comment by Shr1xy** [comment]
I've deleted all the mods which you wrote. Downloaded the mod "more save slots". After 1 hour play I got crash again after trying to save game after leaving the city. Added log.
[log.zip](https://github.com/user-attachments/files/17659983/log.zip)

**Comment by BreakyZ** [comment]
get "msu launcher" from nexus

**Comment by Shr1xy** [comment]
Started a new company via “msu launcher”. In 2 hours no crashes.
