### ISSUE TITLE
[BUG] Same bug as in #182, but with logs this time. for description look for #182

### ISSUE THREAD

**Issue by boomber12321** [Battle-Brothers-Legends/Legends-Bugs#208]
* **Versions**
 Game: [e.g. 1.5.0.15]
 Legends [e.g. 18.1.1]

* **Describe the bug**
Often get crash when saving, and the save will be corrupted. Increasing in frequency until it happens after every other fight. 

* **Your log**
Please post your log so we can help. 
Your log is found in: ```C:\Users\YourName\Documents\Battle Brothers\log.html```
The log is constantly updated during game and is reset each time you open the game and it is best to upload the log when the error first occurred.
[Battle Brothers 1.5.0.15.zip](https://github.com/user-attachments/files/17896121/Battle.Brothers.1.5.0.15.zip)

**YOUR BUG REPORT IS NOT HELPFUL WITHOUT THE LOG, SO PLEASE UPLOAD IT**
* **To Reproduce**
1. play the game
2. save the game
3. crash, critical exception occurred 
4. reload
5. save is corrupted
6. lose progress. with fights in lategame taking an hour each a crash can meam losing up to 2h of progress. 

* **Screenshots**
same as the guy in #182 
Save files. autosave 1,2,3 and manual save 1,2,3
[Ghengis Khan.zip](https://github.com/user-attachments/files/17896082/Ghengis.Khan.zip)

* **Additional context**
Add any other context about the problem, such as links to a discord discussion, here.

**Comment by BreakyZ** [comment]
I cannot read this log. Zip the html file
