### ISSUE TITLE
[BUG]No moves with undead faction

### ISSUE THREAD

**Issue by DDrubin** [Battle-Brothers-Legends/Legends-Bugs#209]
* **Versions**
 Game: [e.g. 1.5.0.15]
 Legends [e.g. 18.2.7]

* **Describe the bug**
After spawn of zombie, I have no moves. Just a static screen of battle. 

* **Your log**
Please post your log so we can help. 

[log.zip](https://github.com/user-attachments/files/17976830/log.zip)

**YOUR BUG REPORT IS NOT HELPFUL WITHOUT THE LOG, SO PLEASE UPLOAD IT**
* **To Reproduce**

1. Start battle against necromancer or undead
2. If undead, you will have no moves from the start.
3. If necromancer, kill someone and wait till he spawns a zombie.
4. No moves from the start of next turn.

* **Screenshots**
![photo_2024-12-02_11-51-30](https://github.com/user-attachments/assets/b360b73f-8d03-4e22-a708-ab58426001de)

* **Additional context**
I'm just trying to flee from an undead faction every time I fight.

**Comment by DDrubin** [comment]
You can fix it by patch. I found one in discord channel. Error fixed.

**Comment by BreakyZ** [comment]
Patch is also in the release files if anyone doesn't have access to discord
