### ISSUE TITLE
Implement a Warning or better Information when you try to enter the Arena with less than three brothers

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#21]
**Problem:**
The game does not warn you when you try to enter the Arena but didn't equip all Arena Collars.
This leads to situations where players accidentally only partly equipped the collars and go into the Arena with only one or two brothers and having to reload or resign the campaign because of this

**Describe the solution you'd like:**
In the dialog window right before you confirm to start the fight in the arena there should be a list of all your brothers that are currently equipped with Arena collars.
![SuggestionArenaDescription](https://user-images.githubusercontent.com/2252464/128082156-cc75da61-8582-4049-8fe2-eeeb1bcb1970.PNG)
The names would be listed where I put the 1, 2 and 3.

Additionally there should be a third button at the bottom when you have not equipped everyone with collars, allowing you to fix that mistake. Currently you can only go through with the fight or cancel that fight for the day.

**Alternative solution:**
A simple warning pop-up where you have to confirm that you want to enter that fight with less than three people.
Similar to how there is now a warning when you lost brothers during a battle and would lose items after looting.

**Comment by Enduriel** [comment]
I quite like this personally, will probably get around to it eventually.
