### ISSUE TITLE
[BUG] Piercing Shot and Cascade are missing from composite_bow and named_goblin_heavy_bow

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/Legends-Bugs#23]
**Versions**
 - Game: [e.g. 1.4.0.49]
 - Legends [e.g. 15.0.1.17c]

**Describe the bug**
The "Piercing Shot" and "Cascade" skills are not added in the `onEquip()` function of the **composite_bow** or the **named_goblin_heavy_bow**, but are added to all other bows.

**To Reproduce**
Have the Piercing Shot perk and equip one of the above mentioned bows. See that the active skill is not available. The reason is that the skill hasn't been added to the weapon in the `onEquip` function, like it has been added to other bows' `onEquip` functions.

**Additional context**
Add the following code to the `onEquip` function:
```
this.addSkill(this.new("scripts/skills/actives/legend_piercing_shot"));
this.addSkill(this.new("scripts/skills/actives/legend_cascade_skill"));
```

**Comment by Enduriel** [comment]
Am strongly considering restructuring weapons to inherit from a base version.
All 1h swords inherit from a 1h sword base etc... it would prevent a lot of stupid stuff like this.
