### ISSUE TITLE
[BUG] Demon Alp help adds skills in onAdded but doesn't remove them correctly in onRemoved. This causes the skill to remain on the character even after the mask is removed.

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/Legends-Bugs#27]
**Versions**
 - Game: [e.g. 1.4.0.49]
 - Legends [e.g. 15.0.1.17c]

File: legend_helmet_demon_alp_helm.nut

Description and reproducing: Equip demon alp mask, to get the skill on your character. Then unequip it and see that the skill remains on the character.

Current code:
```
function onAdded()
{
	this.legend_helmet_upgrade.onAdded();
	local skills = this.getContainer().getActor().getSkills();
	local hasPerk = skills.hasSkill("perk.legend_item_horrify");

	if (!hasPerk)
	{
		skills.add(this.new("scripts/skills/perks/perk_legend_item_horrify"));
	}
}

function onRemoved( _app )
{
	local skills = this.getContainer().getActor().getSkills();
	local hasPerk = skills.hasSkill("perk.legend_item_horrify");
	skills.removeByID("actives.legend_horrific_scream");
	this.legend_helmet_upgrade.onRemoved(_app);
}
```
The onRemoved function does not remove the perk.

Also why are we adding this via perk? Why can't one simply add the active skill and then remove the active skill in onRemoved? Adding it via the perk feels unnecessarily convoluted. (One reason I could think of for doing it via perk is to allow it to be readded on game load, if that is the case, then that would explain this way. In this case, we should remove the perk in onRemoved, not the active).

**Comment by Enduriel** [comment]
You have _no_ idea the headache looking into a not stupid solution to this has caused me. On the bright side once we do work this out, armor and helmet attachments should have a much cleaner and more legible backend.
