### ISSUE TITLE
[BUG] The Ambition for Roster of 6 and -12 can be offered at the same time

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#28]
**Versions**
 - Game: 1.4.0.49
 - Legends 15.0.1.17c

**Describe the bug**
At the very start of the game it is possible to receive the Ambition for "a half dozen men" and the one for "a dozen men" at the same time.
This is redundant and should never occur. You never pick "a dozen men" in this case.

**Screenshots**
![BugDozenHalfDozen](https://user-images.githubusercontent.com/2252464/129441066-65bb6533-2440-4c5d-b00e-55a71add4868.PNG)

**Comment by Enduriel** [comment]
Requires some global flags to keep track of properly.
