### ISSUE TITLE
[BUG] After loading a saved game, enemy parties are invisible while the game is still paused

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#34]
**Versions**
 - Game: 1.4.0.49
 - Legends 15.0.1.18b

**Describe the bug**
When you load a savefile all enemy parties are invisible while the game is paused.
When you unpause after a very short duration they become visible again.
Apparently this is even an issue in vanilla battle brothers.

**To Reproduce**
1. Get close to an enemy party
2. Save the game and return to the main menue
3. Load that saved game
4. The nearby enemy party is invisible for atleast as long as the game remains paused

**Additional context**
Normally this is not a big issue because it fixes itself almost instantly.
However! When you play ironman, try to run away from an enemy party but they catch up to you and ambush you this becomes almost certainly the end of your campaign.
Because of it being an ambush they surround your party leaving you no chance to escape.
And if you Alt+F4 and reload the campaign this enemy party is invisible. So you don't have the option to attack them yourself. So you always end up in an ambush scenario against them.

**Comment by Enduriel** [comment]
I think the best way of doing this would be to make the parties visible only if you weren't ambushed, that way we preserve the state of the campaign during the autosave better.

**Comment by Enduriel** [comment]
I don't think this can actually be done unfortunately.`this.World.uncoverFogOfWar` doesn't reveal non-location entities, and the function that the game uses to reveal an area to a player seems to be hidden in the exe. If you or anyone else figures out a way to do this that'd be great, but if not I'll mark this as a won't fix in a few days.
