### ISSUE TITLE
For Enduriel: Better Battleforged code

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/Legends-Bugs#39]
@Enduriel The current Battleforged perk is coded in a bad way by Overhype. This has led to the issue that when Legends wanted to change the damage reduction, the number had to be changed in like 5 different places. This sometimes led to bugs where the number was forgotten to be changed e.g. in the tooltip of the Status Effect etc. 

Here is a much more streamlined version of the code which only requires 1 number to be changed, which will then automatically update the perk's mechanics and the tooltip of the Status Effect.

`
this.perk_battle_forged <- this.inherit("scripts/skills/skill", {
	m = {
		ArmorPercentageAsReduction = 5
	},
	function create()
	{
		this.m.ID = "perk.battle_forged";
		this.m.Name = this.Const.Strings.PerkName.BattleForged;
		this.m.Description = this.Const.Strings.PerkDescription.BattleForged;
		this.m.Icon = "ui/perks/perk_03.png";
		this.m.Type = this.Const.SkillType.Perk | this.Const.SkillType.StatusEffect;
		this.m.Order = this.Const.SkillOrder.Perk;
		this.m.IsActive = false;
		this.m.IsStacking = false;
		this.m.IsHidden = false;
	}

	function isHidden = function()
	{
		return this.getReductionPercentage() <= 0;
	}

	function getDescription()
	{
		return "Specialize in heavy armor! Armor damage taken is reduced by a percentage equal to [color=" + this.Const.UI.Color.PositiveValue + "]" + this.m.ArmorPercentageAsReduction + "[/color] of the current total armor value of both body and head armor. The heavier your armor and helmet, the more you benefit.";
	}
	
	function getReductionPercentage()
	{
		local armor = this.getContainer().getActor().getArmor(this.Const.BodyPart.Head) + this.getContainer().getActor().getArmor(this.Const.BodyPart.Body);
		return this.Math.floor(armor * this.m.ArmorPercentageAsReduction * 0.01);
	}

	function getTooltip()
	{
		local tooltip = this.skill.getTooltip();

		local reduction = this.getReductionPercentage();
		tooltip.push({
			id = 6,
			type = "text",
			icon = "ui/icons/special.png",
			text = "Only receive [color=" + this.Const.UI.Color.PositiveValue + "]" + (100-reduction) + "%[/color] of any damage to armor from attacks"
		});

		return tooltip;
	}

	function onBeforeDamageReceived ( _attacker, _skill, _hitInfo, _properties )
	{
		if (_attacker != null && _attacker.getID() == this.getContainer().getActor().getID() || _skill != null && !_skill.isAttack())
		{
			return;
		}

		local reduction = this.getReductionPercentage();
		_properties.DamageReceivedArmorMult *= 1.0 - reduction * 0.01;
	}
});
`

**Comment by Enduriel** [comment]
Ty for this, much cleaner way of writing the perk.
