### ISSUE TITLE
Melee damage modifiers not applying to unarmed damage. [BUG]

### ISSUE THREAD

**Issue by Lourne-bb** [Battle-Brothers-Legends/Legends-Bugs#40]
**Versions**
 - Game: 1.4.0.49
 - Legends 15.0.1.18b

**Describe the bug**
Using Berserker origin, newly rolled starts do not apply the % melee damage modifier of traits such as Light, Huge, Lumbering, etc. to the unarmed damage numbers in the hover tooltip.

**To Reproduce**
Roll new Berserker starts, select unarmed training as first skill, compare hand to hand attack tooltips .

**Screenshots**
![image](https://user-images.githubusercontent.com/89305755/130323614-a0c88e38-d80f-4c8a-89fb-094ffd7073f2.png)

I tried to get the screenshots as close as possible on the ini and hp values although there is a bit of variance.

**Comment by Enduriel** [comment]
So this is actually a casualty of a much larger problem in BB as a whole that @LordMidas has fixed with PTR, hoping to get his help on how to fix this and a variety of similar issues due to the way game calculates modifiers for skills.
