### ISSUE TITLE
Remove the ability to scrap famed items

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#44]
**Is your feature request related to a problem? Please describe.**
Famed items are almost never worth scrapping. Even if you don't need them it is better to repair them or sell them as is.
Removing the option to scrap famed items will
- prevent accidentally scrapping famed items
- reduce the number of clicks you do when interacting with famed while toggling between repair and default

**Describe the solution you'd like**
Remove the ability to choose famed items for scrapping. 
They should only ever toggle between Default and "Set to be Repaired".

**Comment by Enduriel** [comment]
I think this is a little excessive and to the point that we're taking away player freedom, I don't think safety rails to this extent are required.
