### ISSUE TITLE
Vala can use staff skills while disarmed

### ISSUE THREAD

**Issue by TheCutestSkinghoul** [Battle-Brothers-Legends/Legends-Bugs#46]
Legends 18b

Vala can use her staff even when disarmed
- currently investigating the extent of this bug and if it affects just the vala or all staffs
![image](https://user-images.githubusercontent.com/87435880/131367954-ec637071-dcae-476d-835a-4a9844c46eba.png)

**Comment by LordMidas** [comment]
I don't see any issue there. The skills are disabled i.e. they are not usable while disarmed. This appears to be the normal state of all weapon skills while disarmed. Here is the code from skill.nut:
```
function isUsable()
	{
		return this.m.IsUsable && this.m.Container.getActor().getCurrentProperties().IsAbleToUseSkills && (!this.m.IsWeaponSkill || this.m.Container.getActor().getCurrentProperties().IsAbleToUseWeaponSkills) && !this.isHidden();
	}
```

This `IsAbleToUseWeaponSkills` boolean is set to false by the Disarmed effect, thereby disabling any use of weapon skills. But the skills remain visible.

**Comment by TheCutestSkinghoul** [comment]
Tested it again today, i can definitely use the staff skills while disarmed, including attacking over 2 tiles.
Might be an interaction with chants that is causing this. Still testing.

**Comment by LordMidas** [comment]
> Tested it again today, i can definitely use the staff skills while disarmed, including attacking over 2 tiles.
> Might be an interaction with chants that is causing this. Still testing.

I think I found the problem. In the staff active skills i.e. `legend_staff_bash.nut` and any other staff skill, please add `this.m.IsWeaponSkill = true`.
