### ISSUE TITLE
[Question] Is it intended that there are two perk trees related to Unarmed combat?

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/Legends-Bugs#48]
**Describe what you think the current issue is**
Currently there are two Unarmed combat trees:

1. gt.Const.Perks.FistTree which exists in z_perks_tree_weapons.nut and contains the following perks: Unarmed Training, Kick, Grapple, Fists Specialization.
2. gt.Const.Perks.FistsClassTree which exists in z_perks_tree_class.nut and contains the following perks: Unarmed Training, Kick, Grapple, Fists Specialization, Unarmed Lunge, Choke, Push the Advantage.

**Suggest how you'd fix this issue**
Perhaps it should simply be a Class tree and not a Weapons tree. This way we avoid the Unarmed tree from appearing on most bros, as in Legends the chance to roll a random Class Tree is low. However, we can still keep the FistsClassTree hardcoded on Brawlers and other relevant backgrounds.

**Comment by Enduriel** [comment]
Luft and I talked about it and we agree that the weapon tree seems out of place, it was only guaranteed on manhunters anyway so I'm just removing it completely.
