### ISSUE TITLE
[BUG] Embalmed appear with western helmets. they should only wear equipment designed for them

### ISSUE THREAD

**Issue by VonKrolockBB** [Battle-Brothers-Legends/Legends-Bugs#52]
**Versions**
 - Game: [e.g. 1.4.0.49]
 - Legends [e.g. 15.0.1.15]

**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**
Add any other context about the problem, such as links to a discord discussion, here.

**Comment by Enduriel** [comment]
I may have fully solved this already in the current live release but I didn't have a save to test on, this is due to missing/incorrectly named brushes rather than northern helmets being meant to spawn on mummies

**Comment by Enduriel** [comment]
Closing this for now as above, if it continues happening reopen please.
