### ISSUE TITLE
Skill.nut needs a system to show ranged distance in green for the sling class of weapon

### ISSUE THREAD

**Issue by TheCutestSkinghoul** [Battle-Brothers-Legends/Legends-Bugs#60]
Original code;
starting line 1142 in skill.nut
	
	if (this.m.IsRanged && myTile.getDistanceTo(_targetTile) > 1)
		{
			if (_targetTile.IsOccupiedByActor)
			{
				ret.push({
					icon = "ui/tooltips/negative.png",
					text = "Distance of " + _targetTile.getDistanceTo(user.getTile())
				});
			}

**Comment by Darxo** [comment]
So this works correctly for all ranged weapons except the Sling class?
I can't figure out what the problem is or what the code has to do with it. Unless "sling" is slang for "ranged"

**Comment by Enduriel** [comment]
Woops sorry, I actually fixed this already lol.

**Comment by LordMidas** [comment]
See related issue #101
