### ISSUE TITLE
Bear Taming skill does not spawn bear upon being taken.

### ISSUE THREAD

**Issue by brantcy** [Battle-Brothers-Legends/Legends-Bugs#61]
**Versions**
 - Game: [e.g. 1.4.0.49]
 - Legends 15.0.1.20g
 - With and also without PTR

**Describe the bug**
Upon level-up choosing bear taming does not spawn a bear in your inventory immediately.  This led to me save scumming and skipping the skill until I got conformation that it should work.  While playing originally my first bear taming perk spawned a bear.  The second character in the run did not spawn a bear upon taking the perk.

Breditor testing on a fresh save saw the delay of receiving a bear until after pause for BOTH the first and second Brother taking the perk.  This behavior was identical on the PTR version.

**Comment by TheCutestSkinghoul** [comment]
Seems to be at least somewhat related to donkeys needing a moment to register extra stash space. Possibly related to gametime.

Suggest moving bear to be a bound skill (see: ranger falcon) to avoid inventory issues and waiting.
