### ISSUE TITLE
quest difficulty calculation for bards(also weapon name generation)[BUG]

### ISSUE THREAD

**Issue by OctavusTao** [Battle-Brothers-Legends/Legends-Bugs#62]
- Game: 1.4.0.49
 - Legends 15.0.1.19

I accepted a level four quest, however the camp is consisted only of several bandit thugs, bandit poachers, and three musicians. Musicians were not heavily armoured nor named, just normal mobs. Fight's difficulty is very low, lower than most level one quests. After the battle, a famed lute dropped among other common drops, the lute's name is also quite interesting. Reward was about 1300 gold, normal payout for a level four quest.

Accept level four quest and proceed to camp, nothing unusual.

Famed lute drop
![image](https://user-images.githubusercontent.com/50324839/132265467-c946b9ee-b564-4a00-8207-6666a85ceee9.png)

**Comment by Enduriel** [comment]
Removed the axe as a possible name from the named lute

**Comment by Enduriel** [comment]
I'm gonna close this for now as the easily reproducible part has been fixed, and the other part may have been fixed with recent party changes, if the quest party issue persists reopen a new issue please.
