### ISSUE TITLE
[BUG] One brother randomly did not receive experience from Camp-Training after caravan trip

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#69]
**Versions**
 - Game: 1.4.0.49
 - Legends 15.0.1.20g

**Describe the bug**
One of my four brothers that I assigned to the training camp during a two-day caravan trip did not receive a single experience point at the end from the training.

**To Reproduce - This is likely NOT reproducable easily.*
But here are the steps I did during this one scenario:
1. Start a new campaign where I am beginning with a solo brother in a small village with a guaranteed caravan mission
2. Sell & Buy some gear and hire three brothers
3. Accept the caravan mission
4. Assign everyone to the training camp
5. Start camping
6. Wait ~2 days until the caravan arrived at the destination (which gave me 144 experience for everyone)
7. Stop Camping (At which point I ended up in the following first screenshot)

**Screenshots**
This Screenshot shows the camping results. I received one injury but only three of my four assigned brothers gained experience.
![BugTrainingCampMissingGuy01](https://user-images.githubusercontent.com/2252464/132799099-61940613-e0d2-4994-be04-a6ba6b9f9cce.PNG)

Immediately after I checked the training camp and confirmed that I had all four assigned to training.
![BugTrainingCampMissingGuy02](https://user-images.githubusercontent.com/2252464/132799087-1e5597ce-79c2-44a7-88c6-b7a7e4f7845d.PNG)

Lastly I confirmed that there was indeed one of the four brothers who did not get any experience. Note here that the right-most brother starts at level four in this campaign and therefor didn't level up from this batch of experience.
![BugTrainingCampMissingGuy03](https://user-images.githubusercontent.com/2252464/132799092-a0ef81ca-042d-4f2a-bfae-672218448b0f.PNG)

**Additional context**
I had this issue rarely happen to me in the past where a random brother did not receive experience from camping. I wanna say roughly once a week when I was actively playing where I noticed it. But this is the first time I made some documentation.

Here is the log:
[log.zip](https://github.com/Battle-Brothers-Legends/Legends-Bugs/files/7141265/log.zip)

**Comment by Enduriel** [comment]
Uncertain if this is actually a bug, I don't think brothers are meant to be guaranteed to gain experience from training.

**Comment by Darxo** [comment]
I just found this code passage. And this is probably where it is decided in an all or nothing way whether someone gained anything at all from the training.
```
[...]
local r = this.Math.min(95, 100 * this.Math.pow(this.m.Camp.getCampTimeHours() / 12.0, 0.6 + 0.1 * bro.getLevel()));

if (this.Math.rand(1, 100) < r)
{
	this.getTrained(bro);
}
[...]
```

If this is the case then I believe there should be a special flavourful one-liner explaining that so-and-so did infact not learn anything during this training session or as slacking off or something.

**Comment by Enduriel** [comment]
>If this is the case then I believe there should be a flavourful one-liner explaining that so-and-so did infact not learn anything during this very long training session or was slacking off or something.\
That seems reasonable, will throw that in.

**Comment by Darxo** [comment]
This issue was adressed in the very recent release according to the patchnotes. So I believe it can be closed.
