### ISSUE TITLE
[BUG] This bandit camp spawned exclusively with dogs and ranged bandits

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#71]
**Versions**
 - Game: 1.4.0.49
 - Legends: 15.0.1.20g

**Describe the bug**
Very early in the game I accepted a 2-Star contract telling me to clear a nearby Bandit Camp. I never been at this position before. When I came close I saw its garrison consists exclusively of ranged bandits and a few dogs.
This seems very wrong as I expect untouched enemy armies and garrisons to always have a healthy mix of frontline and backline.

**Screenshots**
![Balance2StarContractExclusivelyRanged](https://user-images.githubusercontent.com/2252464/132942381-9223e8a2-3a97-4b40-b777-39afe633091b.PNG)

edit:
Here is another random Bandit Camp. In this case their only non-dog frontline consists of one Thug.
![BugToManyRangedEnemies](https://user-images.githubusercontent.com/2252464/132949887-fbc1d1aa-c886-4e47-8848-ffbcab05fb5f.PNG)

**Comment by TheCutestSkinghoul** [comment]
Can you verify if they sent out a patrol recently?
If they did that would explain the strange garrison shift.

**Comment by TheCutestSkinghoul** [comment]
Update: possibly fixed. please reopen if you see this in the next build.
