### ISSUE TITLE
[BUG] When engaging an enemy camp with only one Brother bottom right the battle instantly ends

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#73]
**Versions**
 - Game: 1.4.0.49
 - Legends: 15.0.1.20g

**Describe the bug**
When I try to engage this hostile camp with just one brother who is positioned in the bottom right, the battle instantly ends as if all of my brothers were in reserve.
This only happens when my scout is in the most bottom right corner of the formation. If he is at any other (tested opposite corner, and the two close tiles) then the battle starts as normal.
I also tried another brother bottom right and the battle also instantly ended.

edit: I just tried this with another nearby camp and the same thing happened. Instant-Retreat!

**To Reproduce**
Download the .zip below. Inside is a save and the PTR mod which you need for this
1. Load the day 50 Expert/Expert/Ironman savegame
2. Verify in the inventory that there is only one guy active and he is in the bottom right corner
3. Attack the nearby camp
4. See an instant defeat

**Screenshots**
The is the screen during the battle which ends instantly.
![BugBattleInstantEnding](https://user-images.githubusercontent.com/2252464/132957875-d87cbb32-cafb-4f9c-af0a-2dd22cbb0369.PNG)

This is my formation. I only have one brother active and he is in the bottom right corner of the formation.
![BugBattleInsteadDefeatInventory](https://user-images.githubusercontent.com/2252464/132957867-f56f2740-26c5-48df-ad65-d43dd5c6fceb.PNG)

**Additional context**
Here is the log, my current savefile and the PTR mod which you need to load that savefile.
[log-save-mod.zip](https://github.com/Battle-Brothers-Legends/Legends-Bugs/files/7148340/log-save-mod.zip)

**Comment by Darxo** [comment]
This issue is very likely already fixed.
Apparently it is the same as https://github.com/Battle-Brothers-Legends/Legends-Bugs/issues/65

**Comment by Enduriel** [comment]
> This issue is very likely already fixed.
> Apparently it is the same as https://github.com/Battle-Brothers-Legends/Legends-Bugs/issues/65

Yup
