### ISSUE TITLE
Attacking a camp with all brothers in reserve reveals its defenders instantly with no risk

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#74]
**Describe what you think the current issue is**
If you set all your brothers to be in reserve and attack a camp the battle instantly ends.
However for a brief second you are able to spot the enemy party composition because the whole tactical map is revealed and the camera zooms out. Also the exact amount of enemies is shown at the top.
This allows the player to instantly scout camps with unknown garrisons with no risk of losing their scout to Hellhounds, Vampires, etc.

**Suggest how you'd fix this issue**
Make it so that putting every brother in reserve will be treated as if you had no one in reserve. 
So whenever you get into combat with everyone in reserve then in stead everyone is forced into battle.

**Comment by Darxo** [comment]
@Enduriel I thought an issue that may occur now with the fix.
If everyone is forced into battle then this solution would allow you to cheese more brothers into battle than possible when attacking a camp or an enemy (So including your reserve).
A better solution would probably be to just take the first X brothers and force them into battle where X is the maximum that you are currently allowed to bring into battle.

**Comment by Enduriel** [comment]
Yh I have been considering this as well. I was gonna go with the solution that you just described.
