### ISSUE TITLE
Each perk that adds a skill should have its base AP- and Fatigue cost listed in the perk description.

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#80]
**Is your feature request related to a problem? Please describe.**
Several perks add new skills when you pick them and a very important information to evaluate their usefullness is their AP-  and Fatigue cost.
The only way currently to find out is looking in the game code or allocating that perk which possibly ruins a brother in Ironman runs.

**Describe the solution you'd like**
Define a format for how to describe the cost of the added skill in the perk description.
Then manually add the cost of the skill into the descripion of each perk that adds a new skill.

Example:
**Skillcost:** 3 Action Points / 15 Fatigue

**Comment by Enduriel** [comment]
>  Then manually add the cost of the skill into the descripion of each perk that adds a new skill.

Definitely not that. An automated system might be nice though.
