### ISSUE TITLE
[BUG] Sometimes when aiming at enemies north-east with a ranged weapon they don't count as being behind cover

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#84]
**Versions**
 - Game: e.g. 1.4.0.49
 - Legends: 15.0.1.20i

**Describe the bug**
When you aim with a ranged weapon at enemies you can get a **Line of Fire blocked** penalty when there is any obstacle or entity right in front of them.

However in some situations when aiming north and slightly east you get shots without any penalty on enemies that are behind a cover. There seems to be something wrong in how the game calculates the Line of Fire in those instances.

I have encounters those weird situations several time. I wanna say about 15 times in the last 3 months of playing legends. IIRC almost all of those were from aiming north and then east.

One can only imagine if the same is true for aiming south and then west which would give the enemies a painful advantage without you realizing it.

**Screenshots**
Here you can see my archer (with a Bear hood) is aiming at an enemy with a 2H Mace who is blocked by my SwordSpear Clown brother.
This should not be a clear shot but the game treads it as clear line of sight
![BugNotBehindCover](https://user-images.githubusercontent.com/2252464/133467797-eba2640e-27be-4b54-8bf3-575716392bf0.PNG)

This is a another example from the same fight where the game logic works correctly.
The upper barbarian is here counted as an obstacle even though he seems less in the way as the Clown-Brother from the first screenshot.
![BugLineOfFireThisTimeWOrking](https://user-images.githubusercontent.com/2252464/133467760-34278794-1b3a-450e-b266-5e14595cc105.PNG)

**Comment by Enduriel** [comment]
This needs more testing, I don't think it's actually a bug, the northeast guy is at a bearing of 30 degrees (exactly half of a hex), meaning that the game can easily draw a straight line between them without intersecting the clown guy. Whereas the guy to the easy is somewhere between 60 and 90 degrees which means the game is probably unable to draw a line without intersecting a bunch of other hexes.

**Comment by Darxo** [comment]
It could also be me misunderstanding the cover mechanic and underestimating the games ability to calculate it.

Let's say

- **Blue** = Enemy
- **Black** = Obstacle (Tree or some Actor)

then I always assumed that if you stand in

- **Orange:** the obstacle is blocking your shot reducing accuracy
- **Green:** you have a clear shot on the target

![ArgumentCoverMechanic](https://user-images.githubusercontent.com/2252464/133865655-4284d6a9-560f-491f-b187-166e425690ac.jpg)
 
 Atleast according to this logic the shot in the bug report above should have been blocked by the clown

**Comment by Enduriel** [comment]
>  documented a random counter example where the logic works correctly (as I understand it) even though the the enemy is way more visible to the shooter (if we go with realism)

Uh that new example graphic doesn't factor in the ally who is in LOS
![image](https://user-images.githubusercontent.com/50383024/134330847-d41f6f30-2ac8-4f49-8435-c10654f9b573.png)


I believe the game is actually calculating LOS with this kinda setup: 
![image](https://user-images.githubusercontent.com/50383024/134330754-76a03206-2215-42de-aa18-92b1633a78e2.png)
and therefore works fine.

**Comment by Darxo** [comment]
I made a video showcasing the issue.
Unsurprisingly it is the same exact tile that I get this bugged shot from. And when I move just one tile in either direction then the cover-mechanic works correctly again.
https://drive.google.com/file/d/1sqtv2fHU8eJSKORQGNulsvdbXhzpGsIm/view

**Comment by Enduriel** [comment]
I'll be closing this then since this is a vanilla issue
