### ISSUE TITLE
Moving reserve and dismiss buttons

### ISSUE THREAD

**Issue by FallenBard** [Battle-Brothers-Legends/Legends-Bugs#87]
I think that reserve and original dismiss buttons are obsuring character mini a bit too much and it would do a lot for fashion brothers to move them to another spot if possible. On the pinned screenshot i tried to mark a few possible new positions for button
![Battle brothers](https://user-images.githubusercontent.com/89794205/133780395-60fed196-dea3-4831-97f8-bc13f143b1e1.jpg)
s.

**Comment by Enduriel** [comment]
![image](https://user-images.githubusercontent.com/50383024/134745315-5bae3882-6114-4e27-a727-7f7bb1f4294c.png)
New setup
