### ISSUE TITLE
New trait: Acrophobia

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#89]
**Suggestion**
Add the new trait **Acrophobia**
- Character gains +10 Resolve while on- or below ground-level
- Character gains -5 Resolve for each height-level he is on

I implemented the perk here:
[mod_acrophobia.zip](https://github.com/Battle-Brothers-Legends/Legends-Bugs/files/7193616/mod_acrophobia.zip)

The only thing missing to make it appear in the game is adding this entry in the **character_trait.nut**
```
	[
		"trait.acrophobia",
		"scripts/skills/traits/acrophobia_trait"
	],
```

The best I came up with from the vanilla artwork was a scared guy with a way too big head (in proportion) looking over the wall of a castle. 

**Additional Info:**
At first I didn't think of any traits that would exclude this trait. But It probably doesn't make sense if someone gets **Fearless** and **Acrophobia**. So there should be an exclusion between those.

**Screenshots:**
![Suggestion_Acrophobia](https://user-images.githubusercontent.com/2252464/133957660-bcc670e3-26be-4a1b-b852-bfa57fdb9bf0.PNG)
![Suggestion_Acrophobia1](https://user-images.githubusercontent.com/2252464/133957652-22aae329-c6e8-422d-9ce7-e9c1911d3967.PNG)

:

**Comment by LordMidas** [comment]
Very interesting idea. I'd say the +10 Resolve is a bit too strong on ground level though. Perhaps it should give +5 on ground level and -5 for each height level.
