### ISSUE TITLE
Nomad rotation skill causes game crash

### ISSUE THREAD

**Issue by Enduriel** [Battle-Brothers-Legends/Legends-Bugs#9]
https://discord.com/channels/547043336465154049/547044957547134979/851533317165547551

Nomads attempt to rotate with one another, an error appear "unknown brush requested: throw_sand_circle" and game crashes

**Comment by Enduriel** [comment]
Probably fixed with upcoming build, will mark it that way until evidence proves otherwise.

**Comment by MrDanpo** [comment]
The same problem, but with mummies and barbarians chosen. I left the topic with a screenshot
