### ISSUE TITLE
[Balance] Give the default Quivers a fatigue penalty of 1

### ISSUE THREAD

**Issue by Darxo** [Battle-Brothers-Legends/Legends-Bugs#90]
**Describe what you think the current issue is**
A normal 10/10 Quiver has no Fatigue penalty. 
The Quiver-Slot is never used for anything else so any non-archer/crossbower can chugg a quiver in with no cost whatsoever. 
This non-existent penalty for equipping one promotes a boring/slow playstyle where you equip all your melee characters with a Quiver:
- for the tiny off-chance that your archer runs out of arrows during a battle and your other brothers can drop a quiver
- to gain more storage slots in your inventory even if a quiver is just 5 gold worth

**Suggest how you'd fix this issue**
Give the default quivers a fatigue penalty of 1.

**Alternative Solution**
Make it so quivers grant -1 to melee defense to discourage using them on frontliners.

**Comment by Enduriel** [comment]
We think this change is too insignificant either way to actually have any impact, and it's not worth diverging from vanilla to apply it.
