### ISSUE TITLE
Activities on world map

### ISSUE THREAD

**Issue by wuxiangjinxing** [Battle-Brothers-Legends/Legends-Bugs#91]
Stealth: gain -50% world map speed modifier until being canceled by the player.  But it is harder for hostile roaming parties to notice the player's party just like their sight radii are halved. 

March: gain +50% world map speed modifier for 24 hours.  After that, all members in the player's party get an effect that reduces max stamina by 25%.  The effect lasts for a day.

**Comment by TheCutestSkinghoul** [comment]
Could be integrated as retinue (?)
