### ISSUE TITLE
Charm shouldn't work on Vala Warden

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/Legends-Bugs#95]

**Comment by LordMidas** [comment]
@TheCutestSkinghoul Should I close this? As mentioned in my previous comment, I don't think this can happen.

**Comment by TheCutestSkinghoul** [comment]
> @TheCutestSkinghoul Should I close this? As mentioned in my previous comment, I don't think this can happen.

Yes close it, i'll keep an eye out if it happens
